// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow_federated/proto/v0/computation.proto

package tensorflow_federated_v0

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TensorType_DataType int32

const (
	TensorType_DT_INVALID    TensorType_DataType = 0
	TensorType_DT_FLOAT      TensorType_DataType = 1
	TensorType_DT_DOUBLE     TensorType_DataType = 2
	TensorType_DT_INT32      TensorType_DataType = 3
	TensorType_DT_UINT8      TensorType_DataType = 4
	TensorType_DT_INT16      TensorType_DataType = 5
	TensorType_DT_INT8       TensorType_DataType = 6
	TensorType_DT_STRING     TensorType_DataType = 7
	TensorType_DT_COMPLEX64  TensorType_DataType = 8
	TensorType_DT_INT64      TensorType_DataType = 9
	TensorType_DT_BOOL       TensorType_DataType = 10
	TensorType_DT_QINT8      TensorType_DataType = 11
	TensorType_DT_QUINT8     TensorType_DataType = 12
	TensorType_DT_QINT32     TensorType_DataType = 13
	TensorType_DT_BFLOAT16   TensorType_DataType = 14
	TensorType_DT_QINT16     TensorType_DataType = 15
	TensorType_DT_QUINT16    TensorType_DataType = 16
	TensorType_DT_UINT16     TensorType_DataType = 17
	TensorType_DT_COMPLEX128 TensorType_DataType = 18
	TensorType_DT_HALF       TensorType_DataType = 19
	TensorType_DT_UINT32     TensorType_DataType = 22
	TensorType_DT_UINT64     TensorType_DataType = 23
)

var TensorType_DataType_name = map[int32]string{
	0:  "DT_INVALID",
	1:  "DT_FLOAT",
	2:  "DT_DOUBLE",
	3:  "DT_INT32",
	4:  "DT_UINT8",
	5:  "DT_INT16",
	6:  "DT_INT8",
	7:  "DT_STRING",
	8:  "DT_COMPLEX64",
	9:  "DT_INT64",
	10: "DT_BOOL",
	11: "DT_QINT8",
	12: "DT_QUINT8",
	13: "DT_QINT32",
	14: "DT_BFLOAT16",
	15: "DT_QINT16",
	16: "DT_QUINT16",
	17: "DT_UINT16",
	18: "DT_COMPLEX128",
	19: "DT_HALF",
	22: "DT_UINT32",
	23: "DT_UINT64",
}

var TensorType_DataType_value = map[string]int32{
	"DT_INVALID":    0,
	"DT_FLOAT":      1,
	"DT_DOUBLE":     2,
	"DT_INT32":      3,
	"DT_UINT8":      4,
	"DT_INT16":      5,
	"DT_INT8":       6,
	"DT_STRING":     7,
	"DT_COMPLEX64":  8,
	"DT_INT64":      9,
	"DT_BOOL":       10,
	"DT_QINT8":      11,
	"DT_QUINT8":     12,
	"DT_QINT32":     13,
	"DT_BFLOAT16":   14,
	"DT_QINT16":     15,
	"DT_QUINT16":    16,
	"DT_UINT16":     17,
	"DT_COMPLEX128": 18,
	"DT_HALF":       19,
	"DT_UINT32":     22,
	"DT_UINT64":     23,
}

func (x TensorType_DataType) String() string {
	return proto.EnumName(TensorType_DataType_name, int32(x))
}

func (TensorType_DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{5, 0}
}

type Computation struct {
	Type *Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Computation:
	//	*Computation_Tensorflow
	//	*Computation_Intrinsic
	//	*Computation_Data
	//	*Computation_Lambda
	//	*Computation_Block
	//	*Computation_Reference
	//	*Computation_Call
	//	*Computation_Struct
	//	*Computation_Selection
	//	*Computation_Placement
	Computation          isComputation_Computation `protobuf_oneof:"computation"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Computation) Reset()         { *m = Computation{} }
func (m *Computation) String() string { return proto.CompactTextString(m) }
func (*Computation) ProtoMessage()    {}
func (*Computation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{0}
}

func (m *Computation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Computation.Unmarshal(m, b)
}
func (m *Computation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Computation.Marshal(b, m, deterministic)
}
func (m *Computation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Computation.Merge(m, src)
}
func (m *Computation) XXX_Size() int {
	return xxx_messageInfo_Computation.Size(m)
}
func (m *Computation) XXX_DiscardUnknown() {
	xxx_messageInfo_Computation.DiscardUnknown(m)
}

var xxx_messageInfo_Computation proto.InternalMessageInfo

func (m *Computation) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

type isComputation_Computation interface {
	isComputation_Computation()
}

type Computation_Tensorflow struct {
	Tensorflow *TensorFlow `protobuf:"bytes,2,opt,name=tensorflow,proto3,oneof"`
}

type Computation_Intrinsic struct {
	Intrinsic *Intrinsic `protobuf:"bytes,3,opt,name=intrinsic,proto3,oneof"`
}

type Computation_Data struct {
	Data *Data `protobuf:"bytes,10,opt,name=data,proto3,oneof"`
}

type Computation_Lambda struct {
	Lambda *Lambda `protobuf:"bytes,4,opt,name=lambda,proto3,oneof"`
}

type Computation_Block struct {
	Block *Block `protobuf:"bytes,5,opt,name=block,proto3,oneof"`
}

type Computation_Reference struct {
	Reference *Reference `protobuf:"bytes,6,opt,name=reference,proto3,oneof"`
}

type Computation_Call struct {
	Call *Call `protobuf:"bytes,7,opt,name=call,proto3,oneof"`
}

type Computation_Struct struct {
	Struct *Struct `protobuf:"bytes,8,opt,name=struct,proto3,oneof"`
}

type Computation_Selection struct {
	Selection *Selection `protobuf:"bytes,9,opt,name=selection,proto3,oneof"`
}

type Computation_Placement struct {
	Placement *Placement `protobuf:"bytes,11,opt,name=placement,proto3,oneof"`
}

func (*Computation_Tensorflow) isComputation_Computation() {}

func (*Computation_Intrinsic) isComputation_Computation() {}

func (*Computation_Data) isComputation_Computation() {}

func (*Computation_Lambda) isComputation_Computation() {}

func (*Computation_Block) isComputation_Computation() {}

func (*Computation_Reference) isComputation_Computation() {}

func (*Computation_Call) isComputation_Computation() {}

func (*Computation_Struct) isComputation_Computation() {}

func (*Computation_Selection) isComputation_Computation() {}

func (*Computation_Placement) isComputation_Computation() {}

func (m *Computation) GetComputation() isComputation_Computation {
	if m != nil {
		return m.Computation
	}
	return nil
}

func (m *Computation) GetTensorflow() *TensorFlow {
	if x, ok := m.GetComputation().(*Computation_Tensorflow); ok {
		return x.Tensorflow
	}
	return nil
}

func (m *Computation) GetIntrinsic() *Intrinsic {
	if x, ok := m.GetComputation().(*Computation_Intrinsic); ok {
		return x.Intrinsic
	}
	return nil
}

func (m *Computation) GetData() *Data {
	if x, ok := m.GetComputation().(*Computation_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Computation) GetLambda() *Lambda {
	if x, ok := m.GetComputation().(*Computation_Lambda); ok {
		return x.Lambda
	}
	return nil
}

func (m *Computation) GetBlock() *Block {
	if x, ok := m.GetComputation().(*Computation_Block); ok {
		return x.Block
	}
	return nil
}

func (m *Computation) GetReference() *Reference {
	if x, ok := m.GetComputation().(*Computation_Reference); ok {
		return x.Reference
	}
	return nil
}

func (m *Computation) GetCall() *Call {
	if x, ok := m.GetComputation().(*Computation_Call); ok {
		return x.Call
	}
	return nil
}

func (m *Computation) GetStruct() *Struct {
	if x, ok := m.GetComputation().(*Computation_Struct); ok {
		return x.Struct
	}
	return nil
}

func (m *Computation) GetSelection() *Selection {
	if x, ok := m.GetComputation().(*Computation_Selection); ok {
		return x.Selection
	}
	return nil
}

func (m *Computation) GetPlacement() *Placement {
	if x, ok := m.GetComputation().(*Computation_Placement); ok {
		return x.Placement
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Computation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Computation_Tensorflow)(nil),
		(*Computation_Intrinsic)(nil),
		(*Computation_Data)(nil),
		(*Computation_Lambda)(nil),
		(*Computation_Block)(nil),
		(*Computation_Reference)(nil),
		(*Computation_Call)(nil),
		(*Computation_Struct)(nil),
		(*Computation_Selection)(nil),
		(*Computation_Placement)(nil),
	}
}

type Type struct {
	// Types that are valid to be assigned to Type:
	//	*Type_Function
	//	*Type_Struct
	//	*Type_Sequence
	//	*Type_Tensor
	//	*Type_Abstract
	//	*Type_Placement
	//	*Type_Federated
	Type                 isType_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{1}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

type isType_Type interface {
	isType_Type()
}

type Type_Function struct {
	Function *FunctionType `protobuf:"bytes,1,opt,name=function,proto3,oneof"`
}

type Type_Struct struct {
	Struct *StructType `protobuf:"bytes,2,opt,name=struct,proto3,oneof"`
}

type Type_Sequence struct {
	Sequence *SequenceType `protobuf:"bytes,3,opt,name=sequence,proto3,oneof"`
}

type Type_Tensor struct {
	Tensor *TensorType `protobuf:"bytes,4,opt,name=tensor,proto3,oneof"`
}

type Type_Abstract struct {
	Abstract *AbstractType `protobuf:"bytes,5,opt,name=abstract,proto3,oneof"`
}

type Type_Placement struct {
	Placement *PlacementType `protobuf:"bytes,6,opt,name=placement,proto3,oneof"`
}

type Type_Federated struct {
	Federated *FederatedType `protobuf:"bytes,7,opt,name=federated,proto3,oneof"`
}

func (*Type_Function) isType_Type() {}

func (*Type_Struct) isType_Type() {}

func (*Type_Sequence) isType_Type() {}

func (*Type_Tensor) isType_Type() {}

func (*Type_Abstract) isType_Type() {}

func (*Type_Placement) isType_Type() {}

func (*Type_Federated) isType_Type() {}

func (m *Type) GetType() isType_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Type) GetFunction() *FunctionType {
	if x, ok := m.GetType().(*Type_Function); ok {
		return x.Function
	}
	return nil
}

func (m *Type) GetStruct() *StructType {
	if x, ok := m.GetType().(*Type_Struct); ok {
		return x.Struct
	}
	return nil
}

func (m *Type) GetSequence() *SequenceType {
	if x, ok := m.GetType().(*Type_Sequence); ok {
		return x.Sequence
	}
	return nil
}

func (m *Type) GetTensor() *TensorType {
	if x, ok := m.GetType().(*Type_Tensor); ok {
		return x.Tensor
	}
	return nil
}

func (m *Type) GetAbstract() *AbstractType {
	if x, ok := m.GetType().(*Type_Abstract); ok {
		return x.Abstract
	}
	return nil
}

func (m *Type) GetPlacement() *PlacementType {
	if x, ok := m.GetType().(*Type_Placement); ok {
		return x.Placement
	}
	return nil
}

func (m *Type) GetFederated() *FederatedType {
	if x, ok := m.GetType().(*Type_Federated); ok {
		return x.Federated
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Type) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Type_Function)(nil),
		(*Type_Struct)(nil),
		(*Type_Sequence)(nil),
		(*Type_Tensor)(nil),
		(*Type_Abstract)(nil),
		(*Type_Placement)(nil),
		(*Type_Federated)(nil),
	}
}

type FunctionType struct {
	Parameter            *Type    `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Result               *Type    `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionType) Reset()         { *m = FunctionType{} }
func (m *FunctionType) String() string { return proto.CompactTextString(m) }
func (*FunctionType) ProtoMessage()    {}
func (*FunctionType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{2}
}

func (m *FunctionType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionType.Unmarshal(m, b)
}
func (m *FunctionType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionType.Marshal(b, m, deterministic)
}
func (m *FunctionType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionType.Merge(m, src)
}
func (m *FunctionType) XXX_Size() int {
	return xxx_messageInfo_FunctionType.Size(m)
}
func (m *FunctionType) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionType.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionType proto.InternalMessageInfo

func (m *FunctionType) GetParameter() *Type {
	if m != nil {
		return m.Parameter
	}
	return nil
}

func (m *FunctionType) GetResult() *Type {
	if m != nil {
		return m.Result
	}
	return nil
}

type StructType struct {
	Element              []*StructType_Element `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StructType) Reset()         { *m = StructType{} }
func (m *StructType) String() string { return proto.CompactTextString(m) }
func (*StructType) ProtoMessage()    {}
func (*StructType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{3}
}

func (m *StructType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructType.Unmarshal(m, b)
}
func (m *StructType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructType.Marshal(b, m, deterministic)
}
func (m *StructType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructType.Merge(m, src)
}
func (m *StructType) XXX_Size() int {
	return xxx_messageInfo_StructType.Size(m)
}
func (m *StructType) XXX_DiscardUnknown() {
	xxx_messageInfo_StructType.DiscardUnknown(m)
}

var xxx_messageInfo_StructType proto.InternalMessageInfo

func (m *StructType) GetElement() []*StructType_Element {
	if m != nil {
		return m.Element
	}
	return nil
}

type StructType_Element struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Type    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructType_Element) Reset()         { *m = StructType_Element{} }
func (m *StructType_Element) String() string { return proto.CompactTextString(m) }
func (*StructType_Element) ProtoMessage()    {}
func (*StructType_Element) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{3, 0}
}

func (m *StructType_Element) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructType_Element.Unmarshal(m, b)
}
func (m *StructType_Element) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructType_Element.Marshal(b, m, deterministic)
}
func (m *StructType_Element) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructType_Element.Merge(m, src)
}
func (m *StructType_Element) XXX_Size() int {
	return xxx_messageInfo_StructType_Element.Size(m)
}
func (m *StructType_Element) XXX_DiscardUnknown() {
	xxx_messageInfo_StructType_Element.DiscardUnknown(m)
}

var xxx_messageInfo_StructType_Element proto.InternalMessageInfo

func (m *StructType_Element) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StructType_Element) GetValue() *Type {
	if m != nil {
		return m.Value
	}
	return nil
}

type SequenceType struct {
	Element              *Type    `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SequenceType) Reset()         { *m = SequenceType{} }
func (m *SequenceType) String() string { return proto.CompactTextString(m) }
func (*SequenceType) ProtoMessage()    {}
func (*SequenceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{4}
}

func (m *SequenceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequenceType.Unmarshal(m, b)
}
func (m *SequenceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequenceType.Marshal(b, m, deterministic)
}
func (m *SequenceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceType.Merge(m, src)
}
func (m *SequenceType) XXX_Size() int {
	return xxx_messageInfo_SequenceType.Size(m)
}
func (m *SequenceType) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceType.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceType proto.InternalMessageInfo

func (m *SequenceType) GetElement() *Type {
	if m != nil {
		return m.Element
	}
	return nil
}

type TensorType struct {
	Dtype                TensorType_DataType `protobuf:"varint,1,opt,name=dtype,proto3,enum=tensorflow_federated.v0.TensorType_DataType" json:"dtype,omitempty"`
	Dims                 []int64             `protobuf:"varint,2,rep,packed,name=dims,proto3" json:"dims,omitempty"`
	UnknownRank          bool                `protobuf:"varint,3,opt,name=unknown_rank,json=unknownRank,proto3" json:"unknown_rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TensorType) Reset()         { *m = TensorType{} }
func (m *TensorType) String() string { return proto.CompactTextString(m) }
func (*TensorType) ProtoMessage()    {}
func (*TensorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{5}
}

func (m *TensorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorType.Unmarshal(m, b)
}
func (m *TensorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorType.Marshal(b, m, deterministic)
}
func (m *TensorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorType.Merge(m, src)
}
func (m *TensorType) XXX_Size() int {
	return xxx_messageInfo_TensorType.Size(m)
}
func (m *TensorType) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorType.DiscardUnknown(m)
}

var xxx_messageInfo_TensorType proto.InternalMessageInfo

func (m *TensorType) GetDtype() TensorType_DataType {
	if m != nil {
		return m.Dtype
	}
	return TensorType_DT_INVALID
}

func (m *TensorType) GetDims() []int64 {
	if m != nil {
		return m.Dims
	}
	return nil
}

func (m *TensorType) GetUnknownRank() bool {
	if m != nil {
		return m.UnknownRank
	}
	return false
}

type AbstractType struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AbstractType) Reset()         { *m = AbstractType{} }
func (m *AbstractType) String() string { return proto.CompactTextString(m) }
func (*AbstractType) ProtoMessage()    {}
func (*AbstractType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{6}
}

func (m *AbstractType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AbstractType.Unmarshal(m, b)
}
func (m *AbstractType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AbstractType.Marshal(b, m, deterministic)
}
func (m *AbstractType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AbstractType.Merge(m, src)
}
func (m *AbstractType) XXX_Size() int {
	return xxx_messageInfo_AbstractType.Size(m)
}
func (m *AbstractType) XXX_DiscardUnknown() {
	xxx_messageInfo_AbstractType.DiscardUnknown(m)
}

var xxx_messageInfo_AbstractType proto.InternalMessageInfo

func (m *AbstractType) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type PlacementSpec struct {
	// Types that are valid to be assigned to Placement:
	//	*PlacementSpec_Label
	//	*PlacementSpec_Value
	Placement            isPlacementSpec_Placement `protobuf_oneof:"placement"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PlacementSpec) Reset()         { *m = PlacementSpec{} }
func (m *PlacementSpec) String() string { return proto.CompactTextString(m) }
func (*PlacementSpec) ProtoMessage()    {}
func (*PlacementSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{7}
}

func (m *PlacementSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacementSpec.Unmarshal(m, b)
}
func (m *PlacementSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacementSpec.Marshal(b, m, deterministic)
}
func (m *PlacementSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacementSpec.Merge(m, src)
}
func (m *PlacementSpec) XXX_Size() int {
	return xxx_messageInfo_PlacementSpec.Size(m)
}
func (m *PlacementSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacementSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PlacementSpec proto.InternalMessageInfo

type isPlacementSpec_Placement interface {
	isPlacementSpec_Placement()
}

type PlacementSpec_Label struct {
	Label *PlacementLabel `protobuf:"bytes,1,opt,name=label,proto3,oneof"`
}

type PlacementSpec_Value struct {
	Value *Placement `protobuf:"bytes,2,opt,name=value,proto3,oneof"`
}

func (*PlacementSpec_Label) isPlacementSpec_Placement() {}

func (*PlacementSpec_Value) isPlacementSpec_Placement() {}

func (m *PlacementSpec) GetPlacement() isPlacementSpec_Placement {
	if m != nil {
		return m.Placement
	}
	return nil
}

func (m *PlacementSpec) GetLabel() *PlacementLabel {
	if x, ok := m.GetPlacement().(*PlacementSpec_Label); ok {
		return x.Label
	}
	return nil
}

func (m *PlacementSpec) GetValue() *Placement {
	if x, ok := m.GetPlacement().(*PlacementSpec_Value); ok {
		return x.Value
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PlacementSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PlacementSpec_Label)(nil),
		(*PlacementSpec_Value)(nil),
	}
}

type PlacementLabel struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlacementLabel) Reset()         { *m = PlacementLabel{} }
func (m *PlacementLabel) String() string { return proto.CompactTextString(m) }
func (*PlacementLabel) ProtoMessage()    {}
func (*PlacementLabel) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{8}
}

func (m *PlacementLabel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacementLabel.Unmarshal(m, b)
}
func (m *PlacementLabel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacementLabel.Marshal(b, m, deterministic)
}
func (m *PlacementLabel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacementLabel.Merge(m, src)
}
func (m *PlacementLabel) XXX_Size() int {
	return xxx_messageInfo_PlacementLabel.Size(m)
}
func (m *PlacementLabel) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacementLabel.DiscardUnknown(m)
}

var xxx_messageInfo_PlacementLabel proto.InternalMessageInfo

func (m *PlacementLabel) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type Placement struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Placement) Reset()         { *m = Placement{} }
func (m *Placement) String() string { return proto.CompactTextString(m) }
func (*Placement) ProtoMessage()    {}
func (*Placement) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{9}
}

func (m *Placement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Placement.Unmarshal(m, b)
}
func (m *Placement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Placement.Marshal(b, m, deterministic)
}
func (m *Placement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Placement.Merge(m, src)
}
func (m *Placement) XXX_Size() int {
	return xxx_messageInfo_Placement.Size(m)
}
func (m *Placement) XXX_DiscardUnknown() {
	xxx_messageInfo_Placement.DiscardUnknown(m)
}

var xxx_messageInfo_Placement proto.InternalMessageInfo

func (m *Placement) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type FederatedType struct {
	Placement            *PlacementSpec `protobuf:"bytes,1,opt,name=placement,proto3" json:"placement,omitempty"`
	AllEqual             bool           `protobuf:"varint,2,opt,name=all_equal,json=allEqual,proto3" json:"all_equal,omitempty"`
	Member               *Type          `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FederatedType) Reset()         { *m = FederatedType{} }
func (m *FederatedType) String() string { return proto.CompactTextString(m) }
func (*FederatedType) ProtoMessage()    {}
func (*FederatedType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{10}
}

func (m *FederatedType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FederatedType.Unmarshal(m, b)
}
func (m *FederatedType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FederatedType.Marshal(b, m, deterministic)
}
func (m *FederatedType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FederatedType.Merge(m, src)
}
func (m *FederatedType) XXX_Size() int {
	return xxx_messageInfo_FederatedType.Size(m)
}
func (m *FederatedType) XXX_DiscardUnknown() {
	xxx_messageInfo_FederatedType.DiscardUnknown(m)
}

var xxx_messageInfo_FederatedType proto.InternalMessageInfo

func (m *FederatedType) GetPlacement() *PlacementSpec {
	if m != nil {
		return m.Placement
	}
	return nil
}

func (m *FederatedType) GetAllEqual() bool {
	if m != nil {
		return m.AllEqual
	}
	return false
}

func (m *FederatedType) GetMember() *Type {
	if m != nil {
		return m.Member
	}
	return nil
}

type PlacementType struct {
	InstanceLabel        *PlacementLabel `protobuf:"bytes,1,opt,name=instance_label,json=instanceLabel,proto3" json:"instance_label,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PlacementType) Reset()         { *m = PlacementType{} }
func (m *PlacementType) String() string { return proto.CompactTextString(m) }
func (*PlacementType) ProtoMessage()    {}
func (*PlacementType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{11}
}

func (m *PlacementType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacementType.Unmarshal(m, b)
}
func (m *PlacementType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacementType.Marshal(b, m, deterministic)
}
func (m *PlacementType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacementType.Merge(m, src)
}
func (m *PlacementType) XXX_Size() int {
	return xxx_messageInfo_PlacementType.Size(m)
}
func (m *PlacementType) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacementType.DiscardUnknown(m)
}

var xxx_messageInfo_PlacementType proto.InternalMessageInfo

func (m *PlacementType) GetInstanceLabel() *PlacementLabel {
	if m != nil {
		return m.InstanceLabel
	}
	return nil
}

type TensorFlow struct {
	GraphDef             *any.Any            `protobuf:"bytes,1,opt,name=graph_def,json=graphDef,proto3" json:"graph_def,omitempty"`
	InitializeOp         string              `protobuf:"bytes,4,opt,name=initialize_op,json=initializeOp,proto3" json:"initialize_op,omitempty"`
	Parameter            *TensorFlow_Binding `protobuf:"bytes,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Result               *TensorFlow_Binding `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TensorFlow) Reset()         { *m = TensorFlow{} }
func (m *TensorFlow) String() string { return proto.CompactTextString(m) }
func (*TensorFlow) ProtoMessage()    {}
func (*TensorFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{12}
}

func (m *TensorFlow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorFlow.Unmarshal(m, b)
}
func (m *TensorFlow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorFlow.Marshal(b, m, deterministic)
}
func (m *TensorFlow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorFlow.Merge(m, src)
}
func (m *TensorFlow) XXX_Size() int {
	return xxx_messageInfo_TensorFlow.Size(m)
}
func (m *TensorFlow) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorFlow.DiscardUnknown(m)
}

var xxx_messageInfo_TensorFlow proto.InternalMessageInfo

func (m *TensorFlow) GetGraphDef() *any.Any {
	if m != nil {
		return m.GraphDef
	}
	return nil
}

func (m *TensorFlow) GetInitializeOp() string {
	if m != nil {
		return m.InitializeOp
	}
	return ""
}

func (m *TensorFlow) GetParameter() *TensorFlow_Binding {
	if m != nil {
		return m.Parameter
	}
	return nil
}

func (m *TensorFlow) GetResult() *TensorFlow_Binding {
	if m != nil {
		return m.Result
	}
	return nil
}

type TensorFlow_Binding struct {
	// Types that are valid to be assigned to Binding:
	//	*TensorFlow_Binding_Struct
	//	*TensorFlow_Binding_Tensor
	//	*TensorFlow_Binding_Sequence
	Binding              isTensorFlow_Binding_Binding `protobuf_oneof:"binding"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TensorFlow_Binding) Reset()         { *m = TensorFlow_Binding{} }
func (m *TensorFlow_Binding) String() string { return proto.CompactTextString(m) }
func (*TensorFlow_Binding) ProtoMessage()    {}
func (*TensorFlow_Binding) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{12, 0}
}

func (m *TensorFlow_Binding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorFlow_Binding.Unmarshal(m, b)
}
func (m *TensorFlow_Binding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorFlow_Binding.Marshal(b, m, deterministic)
}
func (m *TensorFlow_Binding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorFlow_Binding.Merge(m, src)
}
func (m *TensorFlow_Binding) XXX_Size() int {
	return xxx_messageInfo_TensorFlow_Binding.Size(m)
}
func (m *TensorFlow_Binding) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorFlow_Binding.DiscardUnknown(m)
}

var xxx_messageInfo_TensorFlow_Binding proto.InternalMessageInfo

type isTensorFlow_Binding_Binding interface {
	isTensorFlow_Binding_Binding()
}

type TensorFlow_Binding_Struct struct {
	Struct *TensorFlow_StructBinding `protobuf:"bytes,1,opt,name=struct,proto3,oneof"`
}

type TensorFlow_Binding_Tensor struct {
	Tensor *TensorFlow_TensorBinding `protobuf:"bytes,2,opt,name=tensor,proto3,oneof"`
}

type TensorFlow_Binding_Sequence struct {
	Sequence *TensorFlow_SequenceBinding `protobuf:"bytes,3,opt,name=sequence,proto3,oneof"`
}

func (*TensorFlow_Binding_Struct) isTensorFlow_Binding_Binding() {}

func (*TensorFlow_Binding_Tensor) isTensorFlow_Binding_Binding() {}

func (*TensorFlow_Binding_Sequence) isTensorFlow_Binding_Binding() {}

func (m *TensorFlow_Binding) GetBinding() isTensorFlow_Binding_Binding {
	if m != nil {
		return m.Binding
	}
	return nil
}

func (m *TensorFlow_Binding) GetStruct() *TensorFlow_StructBinding {
	if x, ok := m.GetBinding().(*TensorFlow_Binding_Struct); ok {
		return x.Struct
	}
	return nil
}

func (m *TensorFlow_Binding) GetTensor() *TensorFlow_TensorBinding {
	if x, ok := m.GetBinding().(*TensorFlow_Binding_Tensor); ok {
		return x.Tensor
	}
	return nil
}

func (m *TensorFlow_Binding) GetSequence() *TensorFlow_SequenceBinding {
	if x, ok := m.GetBinding().(*TensorFlow_Binding_Sequence); ok {
		return x.Sequence
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TensorFlow_Binding) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TensorFlow_Binding_Struct)(nil),
		(*TensorFlow_Binding_Tensor)(nil),
		(*TensorFlow_Binding_Sequence)(nil),
	}
}

type TensorFlow_StructBinding struct {
	Element              []*TensorFlow_Binding `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TensorFlow_StructBinding) Reset()         { *m = TensorFlow_StructBinding{} }
func (m *TensorFlow_StructBinding) String() string { return proto.CompactTextString(m) }
func (*TensorFlow_StructBinding) ProtoMessage()    {}
func (*TensorFlow_StructBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{12, 1}
}

func (m *TensorFlow_StructBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorFlow_StructBinding.Unmarshal(m, b)
}
func (m *TensorFlow_StructBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorFlow_StructBinding.Marshal(b, m, deterministic)
}
func (m *TensorFlow_StructBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorFlow_StructBinding.Merge(m, src)
}
func (m *TensorFlow_StructBinding) XXX_Size() int {
	return xxx_messageInfo_TensorFlow_StructBinding.Size(m)
}
func (m *TensorFlow_StructBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorFlow_StructBinding.DiscardUnknown(m)
}

var xxx_messageInfo_TensorFlow_StructBinding proto.InternalMessageInfo

func (m *TensorFlow_StructBinding) GetElement() []*TensorFlow_Binding {
	if m != nil {
		return m.Element
	}
	return nil
}

type TensorFlow_TensorBinding struct {
	// Types that are valid to be assigned to Binding:
	//	*TensorFlow_TensorBinding_TensorName
	Binding              isTensorFlow_TensorBinding_Binding `protobuf_oneof:"binding"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *TensorFlow_TensorBinding) Reset()         { *m = TensorFlow_TensorBinding{} }
func (m *TensorFlow_TensorBinding) String() string { return proto.CompactTextString(m) }
func (*TensorFlow_TensorBinding) ProtoMessage()    {}
func (*TensorFlow_TensorBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{12, 2}
}

func (m *TensorFlow_TensorBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorFlow_TensorBinding.Unmarshal(m, b)
}
func (m *TensorFlow_TensorBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorFlow_TensorBinding.Marshal(b, m, deterministic)
}
func (m *TensorFlow_TensorBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorFlow_TensorBinding.Merge(m, src)
}
func (m *TensorFlow_TensorBinding) XXX_Size() int {
	return xxx_messageInfo_TensorFlow_TensorBinding.Size(m)
}
func (m *TensorFlow_TensorBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorFlow_TensorBinding.DiscardUnknown(m)
}

var xxx_messageInfo_TensorFlow_TensorBinding proto.InternalMessageInfo

type isTensorFlow_TensorBinding_Binding interface {
	isTensorFlow_TensorBinding_Binding()
}

type TensorFlow_TensorBinding_TensorName struct {
	TensorName string `protobuf:"bytes,1,opt,name=tensor_name,json=tensorName,proto3,oneof"`
}

func (*TensorFlow_TensorBinding_TensorName) isTensorFlow_TensorBinding_Binding() {}

func (m *TensorFlow_TensorBinding) GetBinding() isTensorFlow_TensorBinding_Binding {
	if m != nil {
		return m.Binding
	}
	return nil
}

func (m *TensorFlow_TensorBinding) GetTensorName() string {
	if x, ok := m.GetBinding().(*TensorFlow_TensorBinding_TensorName); ok {
		return x.TensorName
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TensorFlow_TensorBinding) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TensorFlow_TensorBinding_TensorName)(nil),
	}
}

type TensorFlow_SequenceBinding struct {
	// Types that are valid to be assigned to Binding:
	//	*TensorFlow_SequenceBinding_VariantTensorName
	Binding              isTensorFlow_SequenceBinding_Binding `protobuf_oneof:"binding"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *TensorFlow_SequenceBinding) Reset()         { *m = TensorFlow_SequenceBinding{} }
func (m *TensorFlow_SequenceBinding) String() string { return proto.CompactTextString(m) }
func (*TensorFlow_SequenceBinding) ProtoMessage()    {}
func (*TensorFlow_SequenceBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{12, 3}
}

func (m *TensorFlow_SequenceBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TensorFlow_SequenceBinding.Unmarshal(m, b)
}
func (m *TensorFlow_SequenceBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TensorFlow_SequenceBinding.Marshal(b, m, deterministic)
}
func (m *TensorFlow_SequenceBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TensorFlow_SequenceBinding.Merge(m, src)
}
func (m *TensorFlow_SequenceBinding) XXX_Size() int {
	return xxx_messageInfo_TensorFlow_SequenceBinding.Size(m)
}
func (m *TensorFlow_SequenceBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_TensorFlow_SequenceBinding.DiscardUnknown(m)
}

var xxx_messageInfo_TensorFlow_SequenceBinding proto.InternalMessageInfo

type isTensorFlow_SequenceBinding_Binding interface {
	isTensorFlow_SequenceBinding_Binding()
}

type TensorFlow_SequenceBinding_VariantTensorName struct {
	VariantTensorName string `protobuf:"bytes,2,opt,name=variant_tensor_name,json=variantTensorName,proto3,oneof"`
}

func (*TensorFlow_SequenceBinding_VariantTensorName) isTensorFlow_SequenceBinding_Binding() {}

func (m *TensorFlow_SequenceBinding) GetBinding() isTensorFlow_SequenceBinding_Binding {
	if m != nil {
		return m.Binding
	}
	return nil
}

func (m *TensorFlow_SequenceBinding) GetVariantTensorName() string {
	if x, ok := m.GetBinding().(*TensorFlow_SequenceBinding_VariantTensorName); ok {
		return x.VariantTensorName
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TensorFlow_SequenceBinding) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TensorFlow_SequenceBinding_VariantTensorName)(nil),
	}
}

type Intrinsic struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Intrinsic) Reset()         { *m = Intrinsic{} }
func (m *Intrinsic) String() string { return proto.CompactTextString(m) }
func (*Intrinsic) ProtoMessage()    {}
func (*Intrinsic) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{13}
}

func (m *Intrinsic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Intrinsic.Unmarshal(m, b)
}
func (m *Intrinsic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Intrinsic.Marshal(b, m, deterministic)
}
func (m *Intrinsic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Intrinsic.Merge(m, src)
}
func (m *Intrinsic) XXX_Size() int {
	return xxx_messageInfo_Intrinsic.Size(m)
}
func (m *Intrinsic) XXX_DiscardUnknown() {
	xxx_messageInfo_Intrinsic.DiscardUnknown(m)
}

var xxx_messageInfo_Intrinsic proto.InternalMessageInfo

func (m *Intrinsic) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type Lambda struct {
	ParameterName        string       `protobuf:"bytes,1,opt,name=parameter_name,json=parameterName,proto3" json:"parameter_name,omitempty"`
	Result               *Computation `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Lambda) Reset()         { *m = Lambda{} }
func (m *Lambda) String() string { return proto.CompactTextString(m) }
func (*Lambda) ProtoMessage()    {}
func (*Lambda) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{14}
}

func (m *Lambda) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lambda.Unmarshal(m, b)
}
func (m *Lambda) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lambda.Marshal(b, m, deterministic)
}
func (m *Lambda) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lambda.Merge(m, src)
}
func (m *Lambda) XXX_Size() int {
	return xxx_messageInfo_Lambda.Size(m)
}
func (m *Lambda) XXX_DiscardUnknown() {
	xxx_messageInfo_Lambda.DiscardUnknown(m)
}

var xxx_messageInfo_Lambda proto.InternalMessageInfo

func (m *Lambda) GetParameterName() string {
	if m != nil {
		return m.ParameterName
	}
	return ""
}

func (m *Lambda) GetResult() *Computation {
	if m != nil {
		return m.Result
	}
	return nil
}

type Block struct {
	Local                []*Block_Local `protobuf:"bytes,1,rep,name=local,proto3" json:"local,omitempty"`
	Result               *Computation   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{15}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetLocal() []*Block_Local {
	if m != nil {
		return m.Local
	}
	return nil
}

func (m *Block) GetResult() *Computation {
	if m != nil {
		return m.Result
	}
	return nil
}

type Block_Local struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Computation `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block_Local) Reset()         { *m = Block_Local{} }
func (m *Block_Local) String() string { return proto.CompactTextString(m) }
func (*Block_Local) ProtoMessage()    {}
func (*Block_Local) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{15, 0}
}

func (m *Block_Local) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block_Local.Unmarshal(m, b)
}
func (m *Block_Local) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block_Local.Marshal(b, m, deterministic)
}
func (m *Block_Local) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block_Local.Merge(m, src)
}
func (m *Block_Local) XXX_Size() int {
	return xxx_messageInfo_Block_Local.Size(m)
}
func (m *Block_Local) XXX_DiscardUnknown() {
	xxx_messageInfo_Block_Local.DiscardUnknown(m)
}

var xxx_messageInfo_Block_Local proto.InternalMessageInfo

func (m *Block_Local) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Block_Local) GetValue() *Computation {
	if m != nil {
		return m.Value
	}
	return nil
}

type Reference struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reference) Reset()         { *m = Reference{} }
func (m *Reference) String() string { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()    {}
func (*Reference) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{16}
}

func (m *Reference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reference.Unmarshal(m, b)
}
func (m *Reference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reference.Marshal(b, m, deterministic)
}
func (m *Reference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reference.Merge(m, src)
}
func (m *Reference) XXX_Size() int {
	return xxx_messageInfo_Reference.Size(m)
}
func (m *Reference) XXX_DiscardUnknown() {
	xxx_messageInfo_Reference.DiscardUnknown(m)
}

var xxx_messageInfo_Reference proto.InternalMessageInfo

func (m *Reference) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Call struct {
	Function             *Computation `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Argument             *Computation `protobuf:"bytes,2,opt,name=argument,proto3" json:"argument,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{17}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetFunction() *Computation {
	if m != nil {
		return m.Function
	}
	return nil
}

func (m *Call) GetArgument() *Computation {
	if m != nil {
		return m.Argument
	}
	return nil
}

type Struct struct {
	Element              []*Struct_Element `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Struct) Reset()         { *m = Struct{} }
func (m *Struct) String() string { return proto.CompactTextString(m) }
func (*Struct) ProtoMessage()    {}
func (*Struct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{18}
}

func (m *Struct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Struct.Unmarshal(m, b)
}
func (m *Struct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Struct.Marshal(b, m, deterministic)
}
func (m *Struct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Struct.Merge(m, src)
}
func (m *Struct) XXX_Size() int {
	return xxx_messageInfo_Struct.Size(m)
}
func (m *Struct) XXX_DiscardUnknown() {
	xxx_messageInfo_Struct.DiscardUnknown(m)
}

var xxx_messageInfo_Struct proto.InternalMessageInfo

func (m *Struct) GetElement() []*Struct_Element {
	if m != nil {
		return m.Element
	}
	return nil
}

type Struct_Element struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Computation `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Struct_Element) Reset()         { *m = Struct_Element{} }
func (m *Struct_Element) String() string { return proto.CompactTextString(m) }
func (*Struct_Element) ProtoMessage()    {}
func (*Struct_Element) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{18, 0}
}

func (m *Struct_Element) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Struct_Element.Unmarshal(m, b)
}
func (m *Struct_Element) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Struct_Element.Marshal(b, m, deterministic)
}
func (m *Struct_Element) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Struct_Element.Merge(m, src)
}
func (m *Struct_Element) XXX_Size() int {
	return xxx_messageInfo_Struct_Element.Size(m)
}
func (m *Struct_Element) XXX_DiscardUnknown() {
	xxx_messageInfo_Struct_Element.DiscardUnknown(m)
}

var xxx_messageInfo_Struct_Element proto.InternalMessageInfo

func (m *Struct_Element) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Struct_Element) GetValue() *Computation {
	if m != nil {
		return m.Value
	}
	return nil
}

type Selection struct {
	Source *Computation `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Types that are valid to be assigned to Selection:
	//	*Selection_Name
	//	*Selection_Index
	Selection            isSelection_Selection `protobuf_oneof:"selection"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Selection) Reset()         { *m = Selection{} }
func (m *Selection) String() string { return proto.CompactTextString(m) }
func (*Selection) ProtoMessage()    {}
func (*Selection) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{19}
}

func (m *Selection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Selection.Unmarshal(m, b)
}
func (m *Selection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Selection.Marshal(b, m, deterministic)
}
func (m *Selection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Selection.Merge(m, src)
}
func (m *Selection) XXX_Size() int {
	return xxx_messageInfo_Selection.Size(m)
}
func (m *Selection) XXX_DiscardUnknown() {
	xxx_messageInfo_Selection.DiscardUnknown(m)
}

var xxx_messageInfo_Selection proto.InternalMessageInfo

func (m *Selection) GetSource() *Computation {
	if m != nil {
		return m.Source
	}
	return nil
}

type isSelection_Selection interface {
	isSelection_Selection()
}

type Selection_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

type Selection_Index struct {
	Index int32 `protobuf:"varint,3,opt,name=index,proto3,oneof"`
}

func (*Selection_Name) isSelection_Selection() {}

func (*Selection_Index) isSelection_Selection() {}

func (m *Selection) GetSelection() isSelection_Selection {
	if m != nil {
		return m.Selection
	}
	return nil
}

func (m *Selection) GetName() string {
	if x, ok := m.GetSelection().(*Selection_Name); ok {
		return x.Name
	}
	return ""
}

func (m *Selection) GetIndex() int32 {
	if x, ok := m.GetSelection().(*Selection_Index); ok {
		return x.Index
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Selection) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Selection_Name)(nil),
		(*Selection_Index)(nil),
	}
}

type Data struct {
	// Types that are valid to be assigned to Data:
	//	*Data_Uri
	Data                 isData_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9364bc00a64966d, []int{20}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

type isData_Data interface {
	isData_Data()
}

type Data_Uri struct {
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3,oneof"`
}

func (*Data_Uri) isData_Data() {}

func (m *Data) GetData() isData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Data) GetUri() string {
	if x, ok := m.GetData().(*Data_Uri); ok {
		return x.Uri
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Data) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Data_Uri)(nil),
	}
}

func init() {
	proto.RegisterEnum("tensorflow_federated.v0.TensorType_DataType", TensorType_DataType_name, TensorType_DataType_value)
	proto.RegisterType((*Computation)(nil), "tensorflow_federated.v0.Computation")
	proto.RegisterType((*Type)(nil), "tensorflow_federated.v0.Type")
	proto.RegisterType((*FunctionType)(nil), "tensorflow_federated.v0.FunctionType")
	proto.RegisterType((*StructType)(nil), "tensorflow_federated.v0.StructType")
	proto.RegisterType((*StructType_Element)(nil), "tensorflow_federated.v0.StructType.Element")
	proto.RegisterType((*SequenceType)(nil), "tensorflow_federated.v0.SequenceType")
	proto.RegisterType((*TensorType)(nil), "tensorflow_federated.v0.TensorType")
	proto.RegisterType((*AbstractType)(nil), "tensorflow_federated.v0.AbstractType")
	proto.RegisterType((*PlacementSpec)(nil), "tensorflow_federated.v0.PlacementSpec")
	proto.RegisterType((*PlacementLabel)(nil), "tensorflow_federated.v0.PlacementLabel")
	proto.RegisterType((*Placement)(nil), "tensorflow_federated.v0.Placement")
	proto.RegisterType((*FederatedType)(nil), "tensorflow_federated.v0.FederatedType")
	proto.RegisterType((*PlacementType)(nil), "tensorflow_federated.v0.PlacementType")
	proto.RegisterType((*TensorFlow)(nil), "tensorflow_federated.v0.TensorFlow")
	proto.RegisterType((*TensorFlow_Binding)(nil), "tensorflow_federated.v0.TensorFlow.Binding")
	proto.RegisterType((*TensorFlow_StructBinding)(nil), "tensorflow_federated.v0.TensorFlow.StructBinding")
	proto.RegisterType((*TensorFlow_TensorBinding)(nil), "tensorflow_federated.v0.TensorFlow.TensorBinding")
	proto.RegisterType((*TensorFlow_SequenceBinding)(nil), "tensorflow_federated.v0.TensorFlow.SequenceBinding")
	proto.RegisterType((*Intrinsic)(nil), "tensorflow_federated.v0.Intrinsic")
	proto.RegisterType((*Lambda)(nil), "tensorflow_federated.v0.Lambda")
	proto.RegisterType((*Block)(nil), "tensorflow_federated.v0.Block")
	proto.RegisterType((*Block_Local)(nil), "tensorflow_federated.v0.Block.Local")
	proto.RegisterType((*Reference)(nil), "tensorflow_federated.v0.Reference")
	proto.RegisterType((*Call)(nil), "tensorflow_federated.v0.Call")
	proto.RegisterType((*Struct)(nil), "tensorflow_federated.v0.Struct")
	proto.RegisterType((*Struct_Element)(nil), "tensorflow_federated.v0.Struct.Element")
	proto.RegisterType((*Selection)(nil), "tensorflow_federated.v0.Selection")
	proto.RegisterType((*Data)(nil), "tensorflow_federated.v0.Data")
}

func init() {
	proto.RegisterFile("tensorflow_federated/proto/v0/computation.proto", fileDescriptor_f9364bc00a64966d)
}

var fileDescriptor_f9364bc00a64966d = []byte{
	// 1404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdd, 0x72, 0xdb, 0xc4,
	0x17, 0xb7, 0xfc, 0xad, 0x63, 0x3b, 0x55, 0xb7, 0x9d, 0xd6, 0xff, 0xfc, 0xa7, 0xb4, 0x55, 0x3f,
	0x67, 0xca, 0x38, 0xb5, 0x53, 0x4c, 0xf9, 0xe8, 0xd0, 0x38, 0x4e, 0x6a, 0x53, 0x93, 0xb4, 0x8a,
	0x5b, 0xe0, 0x4a, 0xb3, 0x96, 0xd7, 0x41, 0x93, 0xb5, 0xe4, 0xca, 0x72, 0x4a, 0xb8, 0x83, 0xe1,
	0x8a, 0x37, 0xe0, 0x05, 0x60, 0x78, 0x09, 0x5e, 0x82, 0x3b, 0x66, 0xb8, 0xe4, 0x8a, 0x97, 0x60,
	0xf6, 0x43, 0x1f, 0x49, 0xe3, 0x4a, 0xa1, 0x77, 0xda, 0xdd, 0xdf, 0xef, 0xa7, 0x73, 0x76, 0xcf,
	0x9e, 0x73, 0x16, 0xd6, 0x7c, 0xe2, 0xcc, 0x5d, 0x6f, 0x42, 0xdd, 0xd7, 0xe6, 0x84, 0x8c, 0x89,
	0x87, 0x7d, 0x32, 0x5e, 0x9b, 0x79, 0xae, 0xef, 0xae, 0x1d, 0xde, 0x5f, 0xb3, 0xdc, 0xe9, 0x6c,
	0xe1, 0x63, 0xdf, 0x76, 0x9d, 0x06, 0x9f, 0x44, 0x97, 0x4f, 0x23, 0x34, 0x0e, 0xef, 0xaf, 0xfe,
	0x6f, 0xdf, 0x75, 0xf7, 0x29, 0x11, 0xdc, 0xd1, 0x62, 0xb2, 0x86, 0x9d, 0x23, 0xc1, 0xd1, 0x7f,
	0x2f, 0x40, 0x65, 0x33, 0x52, 0x42, 0x4d, 0xc8, 0xfb, 0x47, 0x33, 0x52, 0x57, 0xae, 0x29, 0x77,
	0x2b, 0xad, 0x2b, 0x8d, 0x25, 0x92, 0x8d, 0xe1, 0xd1, 0x8c, 0x18, 0x1c, 0x8a, 0xb6, 0x00, 0x22,
	0x54, 0x3d, 0xcb, 0x89, 0x37, 0x96, 0x13, 0xf9, 0xfc, 0x36, 0x75, 0x5f, 0xf7, 0x32, 0x46, 0x8c,
	0x88, 0x3a, 0xa0, 0xda, 0x8e, 0xef, 0xd9, 0xce, 0xdc, 0xb6, 0xea, 0x39, 0xae, 0xa2, 0x2f, 0x55,
	0xe9, 0x07, 0xc8, 0x5e, 0xc6, 0x88, 0x68, 0x68, 0x1d, 0xf2, 0x63, 0xec, 0xe3, 0x3a, 0x24, 0x58,
	0xdf, 0xc5, 0x3e, 0xee, 0x65, 0x0c, 0x0e, 0x46, 0x1f, 0x41, 0x91, 0xe2, 0xe9, 0x68, 0x8c, 0xeb,
	0x79, 0x4e, 0xbb, 0xba, 0x94, 0x36, 0xe0, 0xb0, 0x5e, 0xc6, 0x90, 0x04, 0xd4, 0x86, 0xc2, 0x88,
	0xba, 0xd6, 0x41, 0xbd, 0xc0, 0x99, 0xef, 0x2d, 0x65, 0x76, 0x18, 0xaa, 0x97, 0x31, 0x04, 0x9c,
	0xf9, 0xea, 0x91, 0x09, 0xf1, 0x88, 0x63, 0x91, 0x7a, 0x31, 0xc1, 0x57, 0x23, 0x40, 0x32, 0x5f,
	0x43, 0x1a, 0xf3, 0xd5, 0xc2, 0x94, 0xd6, 0x4b, 0x09, 0xbe, 0x6e, 0x62, 0x4a, 0x99, 0xaf, 0x0c,
	0xcc, 0x7c, 0x9d, 0xfb, 0xde, 0xc2, 0xf2, 0xeb, 0xe5, 0x04, 0x5f, 0xf7, 0x38, 0x8c, 0xf9, 0x2a,
	0x08, 0xcc, 0xe6, 0x39, 0xa1, 0xc4, 0x62, 0x61, 0x52, 0x57, 0x13, 0x6c, 0xde, 0x0b, 0x90, 0xcc,
	0xe6, 0x90, 0xc6, 0x34, 0x66, 0x14, 0x5b, 0x64, 0x4a, 0x1c, 0xbf, 0x5e, 0x49, 0xd0, 0x78, 0x16,
	0x20, 0x99, 0x46, 0x48, 0xeb, 0xd4, 0xa0, 0x12, 0x0b, 0x7d, 0xfd, 0x9f, 0x1c, 0xe4, 0x59, 0x30,
	0xa2, 0x4d, 0x28, 0x4f, 0x16, 0x8e, 0x30, 0x4f, 0x44, 0xef, 0xad, 0xa5, 0xd2, 0xdb, 0x12, 0xc8,
	0x88, 0xbd, 0x8c, 0x11, 0x12, 0xd1, 0xa3, 0x70, 0x7f, 0x92, 0xe2, 0x58, 0xec, 0x8f, 0x14, 0x08,
	0xf6, 0x68, 0x13, 0xca, 0x73, 0xf2, 0x6a, 0xc1, 0x8f, 0x35, 0x97, 0x60, 0xc3, 0x9e, 0x04, 0x06,
	0x36, 0x04, 0x44, 0x66, 0x83, 0xe0, 0xc8, 0x78, 0x4c, 0xba, 0x4b, 0x81, 0x0d, 0x02, 0xc5, 0x6c,
	0xc0, 0xa3, 0xb9, 0xef, 0x61, 0xcb, 0x97, 0x61, 0xb9, 0xdc, 0x86, 0x0d, 0x09, 0x0c, 0x6c, 0x08,
	0x88, 0x68, 0x3b, 0x7e, 0x50, 0x22, 0x40, 0x6f, 0x27, 0x1f, 0x94, 0x94, 0x89, 0xa8, 0x4c, 0x27,
	0x84, 0xca, 0x48, 0x5d, 0xae, 0xb3, 0x1d, 0x0c, 0x02, 0x9d, 0x70, 0xb5, 0x53, 0x14, 0x69, 0x49,
	0xff, 0x41, 0x81, 0x6a, 0xfc, 0xf0, 0xd0, 0x27, 0xa0, 0xce, 0xb0, 0x87, 0xa7, 0xc4, 0x27, 0x5e,
	0xba, 0xa4, 0x15, 0xe1, 0xd1, 0x07, 0x50, 0xf4, 0xc8, 0x7c, 0x41, 0x83, 0xd3, 0x4e, 0x60, 0x4a,
	0xb0, 0xfe, 0xab, 0x02, 0x10, 0x1d, 0x3f, 0xda, 0x82, 0x12, 0xa1, 0x62, 0xa7, 0x94, 0x6b, 0xb9,
	0xbb, 0x95, 0xd6, 0xbd, 0x14, 0x41, 0xd3, 0xd8, 0x12, 0x14, 0x23, 0xe0, 0xae, 0x1a, 0x50, 0x92,
	0x73, 0x08, 0x41, 0xde, 0xc1, 0x53, 0x91, 0x84, 0x55, 0x83, 0x7f, 0xa3, 0x75, 0x28, 0x1c, 0x62,
	0xba, 0x20, 0xe9, 0x4c, 0x15, 0x58, 0xfd, 0x09, 0x54, 0xe3, 0x61, 0x86, 0x3e, 0x8c, 0x9b, 0x9a,
	0x42, 0x26, 0x40, 0xeb, 0x7f, 0xe5, 0x00, 0xa2, 0x68, 0x43, 0x1d, 0x28, 0x8c, 0xc3, 0x32, 0xb1,
	0xd2, 0x7a, 0x3f, 0x45, 0x84, 0xf2, 0x9c, 0x2b, 0x6c, 0xe3, 0x54, 0xe6, 0xe4, 0xd8, 0x9e, 0xce,
	0xeb, 0xd9, 0x6b, 0xb9, 0xbb, 0x39, 0x83, 0x7f, 0xa3, 0xeb, 0x50, 0x5d, 0x38, 0x07, 0x8e, 0xfb,
	0xda, 0x31, 0x3d, 0xec, 0x1c, 0xf0, 0x3b, 0x54, 0x36, 0x2a, 0x72, 0xce, 0xc0, 0xce, 0x81, 0xfe,
	0x47, 0x16, 0xca, 0x81, 0x14, 0x5a, 0x01, 0xe8, 0x0e, 0xcd, 0xfe, 0xce, 0xcb, 0x8d, 0x41, 0xbf,
	0xab, 0x65, 0x50, 0x15, 0xca, 0xdd, 0xa1, 0xb9, 0x3d, 0xd8, 0xdd, 0x18, 0x6a, 0x0a, 0xaa, 0x81,
	0xda, 0x1d, 0x9a, 0xdd, 0xdd, 0x17, 0x9d, 0xc1, 0x96, 0x96, 0x95, 0x8b, 0xfd, 0x9d, 0xe1, 0x7a,
	0x4b, 0xcb, 0xc9, 0xd1, 0x8b, 0xfe, 0xce, 0xf0, 0xa1, 0x96, 0x8f, 0xd6, 0x9a, 0x6d, 0xad, 0x80,
	0x2a, 0x50, 0x12, 0xa3, 0x87, 0x5a, 0x51, 0xaa, 0xec, 0x0d, 0x8d, 0xfe, 0xce, 0x13, 0xad, 0x84,
	0x34, 0xa8, 0x76, 0x87, 0xe6, 0xe6, 0xee, 0x17, 0xcf, 0x06, 0x5b, 0x5f, 0xb5, 0x1f, 0x68, 0xe5,
	0x88, 0xdb, 0x7e, 0xa0, 0xa9, 0x92, 0xdb, 0xd9, 0xdd, 0x1d, 0x68, 0x20, 0x97, 0x9e, 0x73, 0xa5,
	0x8a, 0x54, 0x7a, 0x2e, 0xfe, 0x59, 0x0d, 0x86, 0xc2, 0xa0, 0x1a, 0x3a, 0x07, 0x15, 0x46, 0xe4,
	0xc6, 0x37, 0xdb, 0xda, 0x4a, 0x6c, 0xbd, 0xd9, 0xd6, 0xce, 0x49, 0x5f, 0x39, 0xbb, 0xd9, 0xd6,
	0x34, 0xb9, 0x2c, 0x87, 0xe7, 0xd1, 0x79, 0xa8, 0x45, 0x76, 0x35, 0x5b, 0x0f, 0x35, 0x24, 0x4d,
	0xe9, 0x6d, 0x0c, 0xb6, 0xb5, 0x0b, 0x31, 0xf8, 0x7a, 0x4b, 0xbb, 0x14, 0x1b, 0xb6, 0x1f, 0x68,
	0x97, 0xf5, 0x9b, 0x50, 0x8d, 0xe7, 0x02, 0x74, 0x11, 0x0a, 0x14, 0x8f, 0x08, 0x95, 0x21, 0x28,
	0x06, 0xfa, 0xcf, 0x0a, 0xd4, 0xc2, 0xcb, 0xbe, 0x37, 0x23, 0x16, 0xfa, 0x2c, 0x8e, 0xab, 0xb4,
	0xee, 0x24, 0xe7, 0x88, 0x01, 0x83, 0xb3, 0x4a, 0xc8, 0x79, 0xe8, 0xe3, 0xe3, 0x61, 0x9d, 0xae,
	0x1a, 0x08, 0x4a, 0xa7, 0x12, 0x4b, 0x52, 0xfa, 0x6d, 0x58, 0x39, 0xfe, 0x8f, 0x25, 0x3e, 0x5c,
	0x01, 0x35, 0xc4, 0x21, 0x0d, 0x72, 0x0b, 0xcf, 0x96, 0x00, 0xf6, 0xa9, 0xff, 0xa6, 0x40, 0xed,
	0x58, 0x1e, 0x42, 0xdd, 0x78, 0x2a, 0x54, 0xd2, 0xa6, 0x42, 0xb6, 0x3b, 0xf1, 0x44, 0xf8, 0x7f,
	0x50, 0x31, 0xa5, 0x26, 0x79, 0xb5, 0xc0, 0x94, 0xfb, 0x5a, 0x36, 0xca, 0x98, 0xd2, 0x2d, 0x36,
	0x66, 0x79, 0x68, 0x4a, 0xa6, 0x23, 0xe2, 0xc9, 0xa2, 0x91, 0x94, 0x87, 0x04, 0x58, 0x37, 0x63,
	0xa7, 0xc1, 0x4d, 0xdd, 0x81, 0x15, 0xdb, 0x99, 0xfb, 0xd8, 0xb1, 0x88, 0xf9, 0x5f, 0x8e, 0xc5,
	0xa8, 0x05, 0x74, 0x3e, 0xd4, 0xff, 0x2e, 0x04, 0xb7, 0x9e, 0xf5, 0x6b, 0xa8, 0x09, 0xea, 0xbe,
	0x87, 0x67, 0xdf, 0x98, 0x63, 0x32, 0x91, 0xca, 0x17, 0x1b, 0xa2, 0xb5, 0x6c, 0x04, 0xad, 0x65,
	0x63, 0xc3, 0x39, 0x32, 0xca, 0x1c, 0xd6, 0x25, 0x13, 0x74, 0x03, 0x6a, 0xb6, 0x63, 0xfb, 0x36,
	0xa6, 0xf6, 0x77, 0xc4, 0x74, 0x67, 0xbc, 0xa4, 0xa9, 0x46, 0x35, 0x9a, 0xdc, 0x9d, 0xa1, 0x7e,
	0x3c, 0x87, 0x8b, 0x38, 0xb8, 0x97, 0xa2, 0x7f, 0x6c, 0x74, 0x6c, 0x67, 0x6c, 0x3b, 0xfb, 0xf1,
	0x8c, 0xbe, 0x19, 0x66, 0xf4, 0xdc, 0xd9, 0x75, 0x24, 0x75, 0xf5, 0xfb, 0x2c, 0x94, 0xe4, 0x1c,
	0x7a, 0x1a, 0x36, 0x04, 0xc2, 0xe1, 0x66, 0x1a, 0x41, 0x91, 0xe6, 0xa5, 0x44, 0xac, 0x3d, 0x78,
	0x1a, 0x56, 0xf6, 0x6c, 0x7a, 0x31, 0xf1, 0x19, 0x13, 0x93, 0x75, 0xfe, 0xf9, 0x1b, 0xbd, 0xc6,
	0x7a, 0x2a, 0xdb, 0x24, 0x27, 0x12, 0x0c, 0x65, 0x3a, 0x2a, 0x94, 0x46, 0x62, 0x7a, 0xf5, 0x25,
	0xd4, 0x8e, 0x79, 0x71, 0x96, 0x2a, 0x77, 0xca, 0xd6, 0x86, 0x55, 0xee, 0x11, 0xd4, 0x8e, 0x39,
	0x84, 0xae, 0x43, 0x45, 0xe8, 0x98, 0x51, 0xc9, 0x8b, 0x5e, 0x06, 0x3b, 0x78, 0x7a, 0xcc, 0xac,
	0x21, 0x9c, 0x3b, 0xe1, 0x00, 0xba, 0x0f, 0x17, 0x0e, 0xb1, 0x67, 0x63, 0xc7, 0x37, 0xe3, 0x42,
	0x59, 0x29, 0x74, 0x5e, 0x2e, 0x0e, 0x4f, 0xd3, 0xfb, 0x3c, 0x5f, 0x56, 0xb4, 0x2c, 0xcb, 0x09,
	0xe1, 0x83, 0xe2, 0x94, 0x9c, 0x30, 0x85, 0xa2, 0xe8, 0xfc, 0xd1, 0x2d, 0x58, 0x09, 0x63, 0x2d,
	0x66, 0xaf, 0x51, 0x0b, 0x67, 0xd9, 0x0f, 0xd0, 0xa7, 0x27, 0xfa, 0x8a, 0x9b, 0xcb, 0x9b, 0xf3,
	0xa8, 0x93, 0x0d, 0xdb, 0x8b, 0x3f, 0x15, 0x28, 0xf0, 0xf7, 0x02, 0x4b, 0x8e, 0xd4, 0xb5, 0x30,
	0x95, 0x3b, 0x7e, 0xf3, 0xed, 0xcf, 0x8b, 0xc6, 0x80, 0x61, 0x0d, 0x41, 0x79, 0x37, 0x1b, 0x56,
	0xbf, 0x84, 0x02, 0x57, 0x3b, 0xb5, 0x15, 0x39, 0x91, 0xb3, 0xd3, 0x29, 0xcb, 0x8e, 0xe4, 0x2a,
	0xa8, 0xe1, 0x7b, 0xe6, 0x34, 0x71, 0xfd, 0x27, 0x05, 0xf2, 0xec, 0xc9, 0x82, 0x1e, 0xbf, 0xd1,
	0xcf, 0xa7, 0xfb, 0x51, 0xd4, 0xcc, 0x3f, 0x86, 0x32, 0xf6, 0xf6, 0x17, 0x3c, 0x66, 0xcf, 0x62,
	0x6a, 0xc8, 0xd2, 0x7f, 0x51, 0xa0, 0x28, 0xae, 0x01, 0xda, 0x38, 0x19, 0xff, 0x77, 0x12, 0xba,
	0xbc, 0x37, 0x3b, 0xbc, 0xaf, 0xdf, 0xde, 0xe1, 0xbd, 0xcb, 0xb6, 0xfe, 0xa8, 0x80, 0x1a, 0xbe,
	0xb9, 0xd8, 0xd9, 0xcf, 0xdd, 0x85, 0x67, 0x91, 0x33, 0x6d, 0x9c, 0xe4, 0xa0, 0x8b, 0xd2, 0xb6,
	0xe0, 0x06, 0x09, 0xeb, 0x2e, 0x41, 0xc1, 0x76, 0xc6, 0xe4, 0x5b, 0x9e, 0x6b, 0x0a, 0xac, 0x08,
	0xf3, 0x21, 0x2b, 0xc2, 0xe1, 0xfb, 0x4e, 0xd7, 0x21, 0xcf, 0x7a, 0x33, 0x84, 0x62, 0x77, 0xa8,
	0x97, 0xe1, 0xb7, 0x88, 0xb5, 0xf0, 0xec, 0xb9, 0x3d, 0x2a, 0xf2, 0x52, 0xb1, 0xfe, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x48, 0x6e, 0x15, 0xc6, 0xdf, 0x10, 0x00, 0x00,
}
