// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow_federated/proto/v0/executor.proto

package tensorflow_federated_v0

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExecuteRequest struct {
	// Types that are valid to be assigned to Request:
	//	*ExecuteRequest_CreateValue
	//	*ExecuteRequest_CreateCall
	//	*ExecuteRequest_CreateStruct
	//	*ExecuteRequest_CreateSelection
	//	*ExecuteRequest_Compute
	//	*ExecuteRequest_Dispose
	//	*ExecuteRequest_SetCardinalities
	Request              isExecuteRequest_Request `protobuf_oneof:"request"`
	SequenceNumber       int32                    `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{0}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

type isExecuteRequest_Request interface {
	isExecuteRequest_Request()
}

type ExecuteRequest_CreateValue struct {
	CreateValue *CreateValueRequest `protobuf:"bytes,1,opt,name=create_value,json=createValue,proto3,oneof"`
}

type ExecuteRequest_CreateCall struct {
	CreateCall *CreateCallRequest `protobuf:"bytes,2,opt,name=create_call,json=createCall,proto3,oneof"`
}

type ExecuteRequest_CreateStruct struct {
	CreateStruct *CreateStructRequest `protobuf:"bytes,3,opt,name=create_struct,json=createStruct,proto3,oneof"`
}

type ExecuteRequest_CreateSelection struct {
	CreateSelection *CreateSelectionRequest `protobuf:"bytes,4,opt,name=create_selection,json=createSelection,proto3,oneof"`
}

type ExecuteRequest_Compute struct {
	Compute *ComputeRequest `protobuf:"bytes,5,opt,name=compute,proto3,oneof"`
}

type ExecuteRequest_Dispose struct {
	Dispose *DisposeRequest `protobuf:"bytes,7,opt,name=dispose,proto3,oneof"`
}

type ExecuteRequest_SetCardinalities struct {
	SetCardinalities *SetCardinalitiesRequest `protobuf:"bytes,8,opt,name=set_cardinalities,json=setCardinalities,proto3,oneof"`
}

func (*ExecuteRequest_CreateValue) isExecuteRequest_Request() {}

func (*ExecuteRequest_CreateCall) isExecuteRequest_Request() {}

func (*ExecuteRequest_CreateStruct) isExecuteRequest_Request() {}

func (*ExecuteRequest_CreateSelection) isExecuteRequest_Request() {}

func (*ExecuteRequest_Compute) isExecuteRequest_Request() {}

func (*ExecuteRequest_Dispose) isExecuteRequest_Request() {}

func (*ExecuteRequest_SetCardinalities) isExecuteRequest_Request() {}

func (m *ExecuteRequest) GetRequest() isExecuteRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ExecuteRequest) GetCreateValue() *CreateValueRequest {
	if x, ok := m.GetRequest().(*ExecuteRequest_CreateValue); ok {
		return x.CreateValue
	}
	return nil
}

func (m *ExecuteRequest) GetCreateCall() *CreateCallRequest {
	if x, ok := m.GetRequest().(*ExecuteRequest_CreateCall); ok {
		return x.CreateCall
	}
	return nil
}

func (m *ExecuteRequest) GetCreateStruct() *CreateStructRequest {
	if x, ok := m.GetRequest().(*ExecuteRequest_CreateStruct); ok {
		return x.CreateStruct
	}
	return nil
}

func (m *ExecuteRequest) GetCreateSelection() *CreateSelectionRequest {
	if x, ok := m.GetRequest().(*ExecuteRequest_CreateSelection); ok {
		return x.CreateSelection
	}
	return nil
}

func (m *ExecuteRequest) GetCompute() *ComputeRequest {
	if x, ok := m.GetRequest().(*ExecuteRequest_Compute); ok {
		return x.Compute
	}
	return nil
}

func (m *ExecuteRequest) GetDispose() *DisposeRequest {
	if x, ok := m.GetRequest().(*ExecuteRequest_Dispose); ok {
		return x.Dispose
	}
	return nil
}

func (m *ExecuteRequest) GetSetCardinalities() *SetCardinalitiesRequest {
	if x, ok := m.GetRequest().(*ExecuteRequest_SetCardinalities); ok {
		return x.SetCardinalities
	}
	return nil
}

func (m *ExecuteRequest) GetSequenceNumber() int32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExecuteRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExecuteRequest_CreateValue)(nil),
		(*ExecuteRequest_CreateCall)(nil),
		(*ExecuteRequest_CreateStruct)(nil),
		(*ExecuteRequest_CreateSelection)(nil),
		(*ExecuteRequest_Compute)(nil),
		(*ExecuteRequest_Dispose)(nil),
		(*ExecuteRequest_SetCardinalities)(nil),
	}
}

type ExecuteResponse struct {
	// Types that are valid to be assigned to Response:
	//	*ExecuteResponse_CreateValue
	//	*ExecuteResponse_CreateCall
	//	*ExecuteResponse_CreateStruct
	//	*ExecuteResponse_CreateSelection
	//	*ExecuteResponse_Compute
	//	*ExecuteResponse_Dispose
	//	*ExecuteResponse_SetCardinalities
	Response             isExecuteResponse_Response `protobuf_oneof:"response"`
	SequenceNumber       int32                      `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ExecuteResponse) Reset()         { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()    {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{1}
}

func (m *ExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteResponse.Unmarshal(m, b)
}
func (m *ExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteResponse.Merge(m, src)
}
func (m *ExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteResponse.Size(m)
}
func (m *ExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteResponse proto.InternalMessageInfo

type isExecuteResponse_Response interface {
	isExecuteResponse_Response()
}

type ExecuteResponse_CreateValue struct {
	CreateValue *CreateValueResponse `protobuf:"bytes,1,opt,name=create_value,json=createValue,proto3,oneof"`
}

type ExecuteResponse_CreateCall struct {
	CreateCall *CreateCallResponse `protobuf:"bytes,2,opt,name=create_call,json=createCall,proto3,oneof"`
}

type ExecuteResponse_CreateStruct struct {
	CreateStruct *CreateStructResponse `protobuf:"bytes,3,opt,name=create_struct,json=createStruct,proto3,oneof"`
}

type ExecuteResponse_CreateSelection struct {
	CreateSelection *CreateSelectionResponse `protobuf:"bytes,4,opt,name=create_selection,json=createSelection,proto3,oneof"`
}

type ExecuteResponse_Compute struct {
	Compute *ComputeResponse `protobuf:"bytes,5,opt,name=compute,proto3,oneof"`
}

type ExecuteResponse_Dispose struct {
	Dispose *DisposeResponse `protobuf:"bytes,7,opt,name=dispose,proto3,oneof"`
}

type ExecuteResponse_SetCardinalities struct {
	SetCardinalities *SetCardinalitiesResponse `protobuf:"bytes,8,opt,name=set_cardinalities,json=setCardinalities,proto3,oneof"`
}

func (*ExecuteResponse_CreateValue) isExecuteResponse_Response() {}

func (*ExecuteResponse_CreateCall) isExecuteResponse_Response() {}

func (*ExecuteResponse_CreateStruct) isExecuteResponse_Response() {}

func (*ExecuteResponse_CreateSelection) isExecuteResponse_Response() {}

func (*ExecuteResponse_Compute) isExecuteResponse_Response() {}

func (*ExecuteResponse_Dispose) isExecuteResponse_Response() {}

func (*ExecuteResponse_SetCardinalities) isExecuteResponse_Response() {}

func (m *ExecuteResponse) GetResponse() isExecuteResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ExecuteResponse) GetCreateValue() *CreateValueResponse {
	if x, ok := m.GetResponse().(*ExecuteResponse_CreateValue); ok {
		return x.CreateValue
	}
	return nil
}

func (m *ExecuteResponse) GetCreateCall() *CreateCallResponse {
	if x, ok := m.GetResponse().(*ExecuteResponse_CreateCall); ok {
		return x.CreateCall
	}
	return nil
}

func (m *ExecuteResponse) GetCreateStruct() *CreateStructResponse {
	if x, ok := m.GetResponse().(*ExecuteResponse_CreateStruct); ok {
		return x.CreateStruct
	}
	return nil
}

func (m *ExecuteResponse) GetCreateSelection() *CreateSelectionResponse {
	if x, ok := m.GetResponse().(*ExecuteResponse_CreateSelection); ok {
		return x.CreateSelection
	}
	return nil
}

func (m *ExecuteResponse) GetCompute() *ComputeResponse {
	if x, ok := m.GetResponse().(*ExecuteResponse_Compute); ok {
		return x.Compute
	}
	return nil
}

func (m *ExecuteResponse) GetDispose() *DisposeResponse {
	if x, ok := m.GetResponse().(*ExecuteResponse_Dispose); ok {
		return x.Dispose
	}
	return nil
}

func (m *ExecuteResponse) GetSetCardinalities() *SetCardinalitiesResponse {
	if x, ok := m.GetResponse().(*ExecuteResponse_SetCardinalities); ok {
		return x.SetCardinalities
	}
	return nil
}

func (m *ExecuteResponse) GetSequenceNumber() int32 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExecuteResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExecuteResponse_CreateValue)(nil),
		(*ExecuteResponse_CreateCall)(nil),
		(*ExecuteResponse_CreateStruct)(nil),
		(*ExecuteResponse_CreateSelection)(nil),
		(*ExecuteResponse_Compute)(nil),
		(*ExecuteResponse_Dispose)(nil),
		(*ExecuteResponse_SetCardinalities)(nil),
	}
}

type CreateValueRequest struct {
	Value                *Value   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateValueRequest) Reset()         { *m = CreateValueRequest{} }
func (m *CreateValueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateValueRequest) ProtoMessage()    {}
func (*CreateValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{2}
}

func (m *CreateValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateValueRequest.Unmarshal(m, b)
}
func (m *CreateValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateValueRequest.Marshal(b, m, deterministic)
}
func (m *CreateValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateValueRequest.Merge(m, src)
}
func (m *CreateValueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateValueRequest.Size(m)
}
func (m *CreateValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateValueRequest proto.InternalMessageInfo

func (m *CreateValueRequest) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type CreateValueResponse struct {
	ValueRef             *ValueRef `protobuf:"bytes,1,opt,name=value_ref,json=valueRef,proto3" json:"value_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateValueResponse) Reset()         { *m = CreateValueResponse{} }
func (m *CreateValueResponse) String() string { return proto.CompactTextString(m) }
func (*CreateValueResponse) ProtoMessage()    {}
func (*CreateValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{3}
}

func (m *CreateValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateValueResponse.Unmarshal(m, b)
}
func (m *CreateValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateValueResponse.Marshal(b, m, deterministic)
}
func (m *CreateValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateValueResponse.Merge(m, src)
}
func (m *CreateValueResponse) XXX_Size() int {
	return xxx_messageInfo_CreateValueResponse.Size(m)
}
func (m *CreateValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateValueResponse proto.InternalMessageInfo

func (m *CreateValueResponse) GetValueRef() *ValueRef {
	if m != nil {
		return m.ValueRef
	}
	return nil
}

type CreateCallRequest struct {
	FunctionRef          *ValueRef `protobuf:"bytes,1,opt,name=function_ref,json=functionRef,proto3" json:"function_ref,omitempty"`
	ArgumentRef          *ValueRef `protobuf:"bytes,2,opt,name=argument_ref,json=argumentRef,proto3" json:"argument_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCallRequest) Reset()         { *m = CreateCallRequest{} }
func (m *CreateCallRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCallRequest) ProtoMessage()    {}
func (*CreateCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{4}
}

func (m *CreateCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCallRequest.Unmarshal(m, b)
}
func (m *CreateCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCallRequest.Marshal(b, m, deterministic)
}
func (m *CreateCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCallRequest.Merge(m, src)
}
func (m *CreateCallRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCallRequest.Size(m)
}
func (m *CreateCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCallRequest proto.InternalMessageInfo

func (m *CreateCallRequest) GetFunctionRef() *ValueRef {
	if m != nil {
		return m.FunctionRef
	}
	return nil
}

func (m *CreateCallRequest) GetArgumentRef() *ValueRef {
	if m != nil {
		return m.ArgumentRef
	}
	return nil
}

type CreateCallResponse struct {
	ValueRef             *ValueRef `protobuf:"bytes,1,opt,name=value_ref,json=valueRef,proto3" json:"value_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCallResponse) Reset()         { *m = CreateCallResponse{} }
func (m *CreateCallResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCallResponse) ProtoMessage()    {}
func (*CreateCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{5}
}

func (m *CreateCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCallResponse.Unmarshal(m, b)
}
func (m *CreateCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCallResponse.Marshal(b, m, deterministic)
}
func (m *CreateCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCallResponse.Merge(m, src)
}
func (m *CreateCallResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCallResponse.Size(m)
}
func (m *CreateCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCallResponse proto.InternalMessageInfo

func (m *CreateCallResponse) GetValueRef() *ValueRef {
	if m != nil {
		return m.ValueRef
	}
	return nil
}

type CreateStructRequest struct {
	Element              []*CreateStructRequest_Element `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CreateStructRequest) Reset()         { *m = CreateStructRequest{} }
func (m *CreateStructRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStructRequest) ProtoMessage()    {}
func (*CreateStructRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{6}
}

func (m *CreateStructRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStructRequest.Unmarshal(m, b)
}
func (m *CreateStructRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStructRequest.Marshal(b, m, deterministic)
}
func (m *CreateStructRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStructRequest.Merge(m, src)
}
func (m *CreateStructRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStructRequest.Size(m)
}
func (m *CreateStructRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStructRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStructRequest proto.InternalMessageInfo

func (m *CreateStructRequest) GetElement() []*CreateStructRequest_Element {
	if m != nil {
		return m.Element
	}
	return nil
}

type CreateStructRequest_Element struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ValueRef             *ValueRef `protobuf:"bytes,2,opt,name=value_ref,json=valueRef,proto3" json:"value_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateStructRequest_Element) Reset()         { *m = CreateStructRequest_Element{} }
func (m *CreateStructRequest_Element) String() string { return proto.CompactTextString(m) }
func (*CreateStructRequest_Element) ProtoMessage()    {}
func (*CreateStructRequest_Element) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{6, 0}
}

func (m *CreateStructRequest_Element) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStructRequest_Element.Unmarshal(m, b)
}
func (m *CreateStructRequest_Element) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStructRequest_Element.Marshal(b, m, deterministic)
}
func (m *CreateStructRequest_Element) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStructRequest_Element.Merge(m, src)
}
func (m *CreateStructRequest_Element) XXX_Size() int {
	return xxx_messageInfo_CreateStructRequest_Element.Size(m)
}
func (m *CreateStructRequest_Element) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStructRequest_Element.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStructRequest_Element proto.InternalMessageInfo

func (m *CreateStructRequest_Element) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateStructRequest_Element) GetValueRef() *ValueRef {
	if m != nil {
		return m.ValueRef
	}
	return nil
}

type CreateStructResponse struct {
	ValueRef             *ValueRef `protobuf:"bytes,1,opt,name=value_ref,json=valueRef,proto3" json:"value_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateStructResponse) Reset()         { *m = CreateStructResponse{} }
func (m *CreateStructResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStructResponse) ProtoMessage()    {}
func (*CreateStructResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{7}
}

func (m *CreateStructResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStructResponse.Unmarshal(m, b)
}
func (m *CreateStructResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStructResponse.Marshal(b, m, deterministic)
}
func (m *CreateStructResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStructResponse.Merge(m, src)
}
func (m *CreateStructResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStructResponse.Size(m)
}
func (m *CreateStructResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStructResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStructResponse proto.InternalMessageInfo

func (m *CreateStructResponse) GetValueRef() *ValueRef {
	if m != nil {
		return m.ValueRef
	}
	return nil
}

type CreateSelectionRequest struct {
	SourceRef *ValueRef `protobuf:"bytes,1,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	// Types that are valid to be assigned to Selection:
	//	*CreateSelectionRequest_Name
	//	*CreateSelectionRequest_Index
	Selection            isCreateSelectionRequest_Selection `protobuf_oneof:"selection"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *CreateSelectionRequest) Reset()         { *m = CreateSelectionRequest{} }
func (m *CreateSelectionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSelectionRequest) ProtoMessage()    {}
func (*CreateSelectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{8}
}

func (m *CreateSelectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSelectionRequest.Unmarshal(m, b)
}
func (m *CreateSelectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSelectionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSelectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSelectionRequest.Merge(m, src)
}
func (m *CreateSelectionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSelectionRequest.Size(m)
}
func (m *CreateSelectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSelectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSelectionRequest proto.InternalMessageInfo

func (m *CreateSelectionRequest) GetSourceRef() *ValueRef {
	if m != nil {
		return m.SourceRef
	}
	return nil
}

type isCreateSelectionRequest_Selection interface {
	isCreateSelectionRequest_Selection()
}

type CreateSelectionRequest_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

type CreateSelectionRequest_Index struct {
	Index int32 `protobuf:"varint,3,opt,name=index,proto3,oneof"`
}

func (*CreateSelectionRequest_Name) isCreateSelectionRequest_Selection() {}

func (*CreateSelectionRequest_Index) isCreateSelectionRequest_Selection() {}

func (m *CreateSelectionRequest) GetSelection() isCreateSelectionRequest_Selection {
	if m != nil {
		return m.Selection
	}
	return nil
}

func (m *CreateSelectionRequest) GetName() string {
	if x, ok := m.GetSelection().(*CreateSelectionRequest_Name); ok {
		return x.Name
	}
	return ""
}

func (m *CreateSelectionRequest) GetIndex() int32 {
	if x, ok := m.GetSelection().(*CreateSelectionRequest_Index); ok {
		return x.Index
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CreateSelectionRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateSelectionRequest_Name)(nil),
		(*CreateSelectionRequest_Index)(nil),
	}
}

type CreateSelectionResponse struct {
	ValueRef             *ValueRef `protobuf:"bytes,1,opt,name=value_ref,json=valueRef,proto3" json:"value_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateSelectionResponse) Reset()         { *m = CreateSelectionResponse{} }
func (m *CreateSelectionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSelectionResponse) ProtoMessage()    {}
func (*CreateSelectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{9}
}

func (m *CreateSelectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSelectionResponse.Unmarshal(m, b)
}
func (m *CreateSelectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSelectionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSelectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSelectionResponse.Merge(m, src)
}
func (m *CreateSelectionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSelectionResponse.Size(m)
}
func (m *CreateSelectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSelectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSelectionResponse proto.InternalMessageInfo

func (m *CreateSelectionResponse) GetValueRef() *ValueRef {
	if m != nil {
		return m.ValueRef
	}
	return nil
}

type ComputeRequest struct {
	ValueRef             *ValueRef `protobuf:"bytes,1,opt,name=value_ref,json=valueRef,proto3" json:"value_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ComputeRequest) Reset()         { *m = ComputeRequest{} }
func (m *ComputeRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeRequest) ProtoMessage()    {}
func (*ComputeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{10}
}

func (m *ComputeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeRequest.Unmarshal(m, b)
}
func (m *ComputeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeRequest.Marshal(b, m, deterministic)
}
func (m *ComputeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeRequest.Merge(m, src)
}
func (m *ComputeRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeRequest.Size(m)
}
func (m *ComputeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeRequest proto.InternalMessageInfo

func (m *ComputeRequest) GetValueRef() *ValueRef {
	if m != nil {
		return m.ValueRef
	}
	return nil
}

type ComputeResponse struct {
	Value                *Value   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeResponse) Reset()         { *m = ComputeResponse{} }
func (m *ComputeResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeResponse) ProtoMessage()    {}
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{11}
}

func (m *ComputeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeResponse.Unmarshal(m, b)
}
func (m *ComputeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeResponse.Marshal(b, m, deterministic)
}
func (m *ComputeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeResponse.Merge(m, src)
}
func (m *ComputeResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeResponse.Size(m)
}
func (m *ComputeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeResponse proto.InternalMessageInfo

func (m *ComputeResponse) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type DisposeRequest struct {
	ValueRef             []*ValueRef `protobuf:"bytes,1,rep,name=value_ref,json=valueRef,proto3" json:"value_ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DisposeRequest) Reset()         { *m = DisposeRequest{} }
func (m *DisposeRequest) String() string { return proto.CompactTextString(m) }
func (*DisposeRequest) ProtoMessage()    {}
func (*DisposeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{12}
}

func (m *DisposeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisposeRequest.Unmarshal(m, b)
}
func (m *DisposeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisposeRequest.Marshal(b, m, deterministic)
}
func (m *DisposeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisposeRequest.Merge(m, src)
}
func (m *DisposeRequest) XXX_Size() int {
	return xxx_messageInfo_DisposeRequest.Size(m)
}
func (m *DisposeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisposeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisposeRequest proto.InternalMessageInfo

func (m *DisposeRequest) GetValueRef() []*ValueRef {
	if m != nil {
		return m.ValueRef
	}
	return nil
}

type DisposeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisposeResponse) Reset()         { *m = DisposeResponse{} }
func (m *DisposeResponse) String() string { return proto.CompactTextString(m) }
func (*DisposeResponse) ProtoMessage()    {}
func (*DisposeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{13}
}

func (m *DisposeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisposeResponse.Unmarshal(m, b)
}
func (m *DisposeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisposeResponse.Marshal(b, m, deterministic)
}
func (m *DisposeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisposeResponse.Merge(m, src)
}
func (m *DisposeResponse) XXX_Size() int {
	return xxx_messageInfo_DisposeResponse.Size(m)
}
func (m *DisposeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisposeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisposeResponse proto.InternalMessageInfo

type SetCardinalitiesRequest struct {
	Cardinalities        []*SetCardinalitiesRequest_Cardinality `protobuf:"bytes,1,rep,name=cardinalities,proto3" json:"cardinalities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *SetCardinalitiesRequest) Reset()         { *m = SetCardinalitiesRequest{} }
func (m *SetCardinalitiesRequest) String() string { return proto.CompactTextString(m) }
func (*SetCardinalitiesRequest) ProtoMessage()    {}
func (*SetCardinalitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{14}
}

func (m *SetCardinalitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCardinalitiesRequest.Unmarshal(m, b)
}
func (m *SetCardinalitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCardinalitiesRequest.Marshal(b, m, deterministic)
}
func (m *SetCardinalitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCardinalitiesRequest.Merge(m, src)
}
func (m *SetCardinalitiesRequest) XXX_Size() int {
	return xxx_messageInfo_SetCardinalitiesRequest.Size(m)
}
func (m *SetCardinalitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCardinalitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCardinalitiesRequest proto.InternalMessageInfo

func (m *SetCardinalitiesRequest) GetCardinalities() []*SetCardinalitiesRequest_Cardinality {
	if m != nil {
		return m.Cardinalities
	}
	return nil
}

type SetCardinalitiesRequest_Cardinality struct {
	Placement            *Placement `protobuf:"bytes,1,opt,name=placement,proto3" json:"placement,omitempty"`
	Cardinality          int32      `protobuf:"varint,2,opt,name=cardinality,proto3" json:"cardinality,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetCardinalitiesRequest_Cardinality) Reset()         { *m = SetCardinalitiesRequest_Cardinality{} }
func (m *SetCardinalitiesRequest_Cardinality) String() string { return proto.CompactTextString(m) }
func (*SetCardinalitiesRequest_Cardinality) ProtoMessage()    {}
func (*SetCardinalitiesRequest_Cardinality) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{14, 0}
}

func (m *SetCardinalitiesRequest_Cardinality) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCardinalitiesRequest_Cardinality.Unmarshal(m, b)
}
func (m *SetCardinalitiesRequest_Cardinality) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCardinalitiesRequest_Cardinality.Marshal(b, m, deterministic)
}
func (m *SetCardinalitiesRequest_Cardinality) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCardinalitiesRequest_Cardinality.Merge(m, src)
}
func (m *SetCardinalitiesRequest_Cardinality) XXX_Size() int {
	return xxx_messageInfo_SetCardinalitiesRequest_Cardinality.Size(m)
}
func (m *SetCardinalitiesRequest_Cardinality) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCardinalitiesRequest_Cardinality.DiscardUnknown(m)
}

var xxx_messageInfo_SetCardinalitiesRequest_Cardinality proto.InternalMessageInfo

func (m *SetCardinalitiesRequest_Cardinality) GetPlacement() *Placement {
	if m != nil {
		return m.Placement
	}
	return nil
}

func (m *SetCardinalitiesRequest_Cardinality) GetCardinality() int32 {
	if m != nil {
		return m.Cardinality
	}
	return 0
}

type SetCardinalitiesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCardinalitiesResponse) Reset()         { *m = SetCardinalitiesResponse{} }
func (m *SetCardinalitiesResponse) String() string { return proto.CompactTextString(m) }
func (*SetCardinalitiesResponse) ProtoMessage()    {}
func (*SetCardinalitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{15}
}

func (m *SetCardinalitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCardinalitiesResponse.Unmarshal(m, b)
}
func (m *SetCardinalitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCardinalitiesResponse.Marshal(b, m, deterministic)
}
func (m *SetCardinalitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCardinalitiesResponse.Merge(m, src)
}
func (m *SetCardinalitiesResponse) XXX_Size() int {
	return xxx_messageInfo_SetCardinalitiesResponse.Size(m)
}
func (m *SetCardinalitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCardinalitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetCardinalitiesResponse proto.InternalMessageInfo

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Tensor
	//	*Value_Computation
	//	*Value_Struct_
	//	*Value_Sequence_
	//	*Value_Federated_
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{16}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_Tensor struct {
	Tensor *any.Any `protobuf:"bytes,1,opt,name=tensor,proto3,oneof"`
}

type Value_Computation struct {
	Computation *Computation `protobuf:"bytes,2,opt,name=computation,proto3,oneof"`
}

type Value_Struct_ struct {
	Struct *Value_Struct `protobuf:"bytes,3,opt,name=struct,proto3,oneof"`
}

type Value_Sequence_ struct {
	Sequence *Value_Sequence `protobuf:"bytes,4,opt,name=sequence,proto3,oneof"`
}

type Value_Federated_ struct {
	Federated *Value_Federated `protobuf:"bytes,5,opt,name=federated,proto3,oneof"`
}

func (*Value_Tensor) isValue_Value() {}

func (*Value_Computation) isValue_Value() {}

func (*Value_Struct_) isValue_Value() {}

func (*Value_Sequence_) isValue_Value() {}

func (*Value_Federated_) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetTensor() *any.Any {
	if x, ok := m.GetValue().(*Value_Tensor); ok {
		return x.Tensor
	}
	return nil
}

func (m *Value) GetComputation() *Computation {
	if x, ok := m.GetValue().(*Value_Computation); ok {
		return x.Computation
	}
	return nil
}

func (m *Value) GetStruct() *Value_Struct {
	if x, ok := m.GetValue().(*Value_Struct_); ok {
		return x.Struct
	}
	return nil
}

func (m *Value) GetSequence() *Value_Sequence {
	if x, ok := m.GetValue().(*Value_Sequence_); ok {
		return x.Sequence
	}
	return nil
}

func (m *Value) GetFederated() *Value_Federated {
	if x, ok := m.GetValue().(*Value_Federated_); ok {
		return x.Federated
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_Tensor)(nil),
		(*Value_Computation)(nil),
		(*Value_Struct_)(nil),
		(*Value_Sequence_)(nil),
		(*Value_Federated_)(nil),
	}
}

type Value_Struct struct {
	Element              []*Value_Struct_Element `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Value_Struct) Reset()         { *m = Value_Struct{} }
func (m *Value_Struct) String() string { return proto.CompactTextString(m) }
func (*Value_Struct) ProtoMessage()    {}
func (*Value_Struct) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{16, 0}
}

func (m *Value_Struct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value_Struct.Unmarshal(m, b)
}
func (m *Value_Struct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value_Struct.Marshal(b, m, deterministic)
}
func (m *Value_Struct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value_Struct.Merge(m, src)
}
func (m *Value_Struct) XXX_Size() int {
	return xxx_messageInfo_Value_Struct.Size(m)
}
func (m *Value_Struct) XXX_DiscardUnknown() {
	xxx_messageInfo_Value_Struct.DiscardUnknown(m)
}

var xxx_messageInfo_Value_Struct proto.InternalMessageInfo

func (m *Value_Struct) GetElement() []*Value_Struct_Element {
	if m != nil {
		return m.Element
	}
	return nil
}

type Value_Struct_Element struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Value   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value_Struct_Element) Reset()         { *m = Value_Struct_Element{} }
func (m *Value_Struct_Element) String() string { return proto.CompactTextString(m) }
func (*Value_Struct_Element) ProtoMessage()    {}
func (*Value_Struct_Element) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{16, 0, 0}
}

func (m *Value_Struct_Element) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value_Struct_Element.Unmarshal(m, b)
}
func (m *Value_Struct_Element) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value_Struct_Element.Marshal(b, m, deterministic)
}
func (m *Value_Struct_Element) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value_Struct_Element.Merge(m, src)
}
func (m *Value_Struct_Element) XXX_Size() int {
	return xxx_messageInfo_Value_Struct_Element.Size(m)
}
func (m *Value_Struct_Element) XXX_DiscardUnknown() {
	xxx_messageInfo_Value_Struct_Element.DiscardUnknown(m)
}

var xxx_messageInfo_Value_Struct_Element proto.InternalMessageInfo

func (m *Value_Struct_Element) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Value_Struct_Element) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Value_Sequence struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Sequence_ZippedSavedModel
	Value                isValue_Sequence_Value `protobuf_oneof:"value"`
	ElementType          *Type                  `protobuf:"bytes,2,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Value_Sequence) Reset()         { *m = Value_Sequence{} }
func (m *Value_Sequence) String() string { return proto.CompactTextString(m) }
func (*Value_Sequence) ProtoMessage()    {}
func (*Value_Sequence) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{16, 1}
}

func (m *Value_Sequence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value_Sequence.Unmarshal(m, b)
}
func (m *Value_Sequence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value_Sequence.Marshal(b, m, deterministic)
}
func (m *Value_Sequence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value_Sequence.Merge(m, src)
}
func (m *Value_Sequence) XXX_Size() int {
	return xxx_messageInfo_Value_Sequence.Size(m)
}
func (m *Value_Sequence) XXX_DiscardUnknown() {
	xxx_messageInfo_Value_Sequence.DiscardUnknown(m)
}

var xxx_messageInfo_Value_Sequence proto.InternalMessageInfo

type isValue_Sequence_Value interface {
	isValue_Sequence_Value()
}

type Value_Sequence_ZippedSavedModel struct {
	ZippedSavedModel []byte `protobuf:"bytes,1,opt,name=zipped_saved_model,json=zippedSavedModel,proto3,oneof"`
}

func (*Value_Sequence_ZippedSavedModel) isValue_Sequence_Value() {}

func (m *Value_Sequence) GetValue() isValue_Sequence_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value_Sequence) GetZippedSavedModel() []byte {
	if x, ok := m.GetValue().(*Value_Sequence_ZippedSavedModel); ok {
		return x.ZippedSavedModel
	}
	return nil
}

func (m *Value_Sequence) GetElementType() *Type {
	if m != nil {
		return m.ElementType
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value_Sequence) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_Sequence_ZippedSavedModel)(nil),
	}
}

type Value_Federated struct {
	Type                 *FederatedType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                []*Value       `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Value_Federated) Reset()         { *m = Value_Federated{} }
func (m *Value_Federated) String() string { return proto.CompactTextString(m) }
func (*Value_Federated) ProtoMessage()    {}
func (*Value_Federated) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{16, 2}
}

func (m *Value_Federated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value_Federated.Unmarshal(m, b)
}
func (m *Value_Federated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value_Federated.Marshal(b, m, deterministic)
}
func (m *Value_Federated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value_Federated.Merge(m, src)
}
func (m *Value_Federated) XXX_Size() int {
	return xxx_messageInfo_Value_Federated.Size(m)
}
func (m *Value_Federated) XXX_DiscardUnknown() {
	xxx_messageInfo_Value_Federated.DiscardUnknown(m)
}

var xxx_messageInfo_Value_Federated proto.InternalMessageInfo

func (m *Value_Federated) GetType() *FederatedType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Value_Federated) GetValue() []*Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type ValueRef struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueRef) Reset()         { *m = ValueRef{} }
func (m *ValueRef) String() string { return proto.CompactTextString(m) }
func (*ValueRef) ProtoMessage()    {}
func (*ValueRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_358ff774449af02a, []int{17}
}

func (m *ValueRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueRef.Unmarshal(m, b)
}
func (m *ValueRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueRef.Marshal(b, m, deterministic)
}
func (m *ValueRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueRef.Merge(m, src)
}
func (m *ValueRef) XXX_Size() int {
	return xxx_messageInfo_ValueRef.Size(m)
}
func (m *ValueRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueRef.DiscardUnknown(m)
}

var xxx_messageInfo_ValueRef proto.InternalMessageInfo

func (m *ValueRef) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ExecuteRequest)(nil), "tensorflow_federated.v0.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "tensorflow_federated.v0.ExecuteResponse")
	proto.RegisterType((*CreateValueRequest)(nil), "tensorflow_federated.v0.CreateValueRequest")
	proto.RegisterType((*CreateValueResponse)(nil), "tensorflow_federated.v0.CreateValueResponse")
	proto.RegisterType((*CreateCallRequest)(nil), "tensorflow_federated.v0.CreateCallRequest")
	proto.RegisterType((*CreateCallResponse)(nil), "tensorflow_federated.v0.CreateCallResponse")
	proto.RegisterType((*CreateStructRequest)(nil), "tensorflow_federated.v0.CreateStructRequest")
	proto.RegisterType((*CreateStructRequest_Element)(nil), "tensorflow_federated.v0.CreateStructRequest.Element")
	proto.RegisterType((*CreateStructResponse)(nil), "tensorflow_federated.v0.CreateStructResponse")
	proto.RegisterType((*CreateSelectionRequest)(nil), "tensorflow_federated.v0.CreateSelectionRequest")
	proto.RegisterType((*CreateSelectionResponse)(nil), "tensorflow_federated.v0.CreateSelectionResponse")
	proto.RegisterType((*ComputeRequest)(nil), "tensorflow_federated.v0.ComputeRequest")
	proto.RegisterType((*ComputeResponse)(nil), "tensorflow_federated.v0.ComputeResponse")
	proto.RegisterType((*DisposeRequest)(nil), "tensorflow_federated.v0.DisposeRequest")
	proto.RegisterType((*DisposeResponse)(nil), "tensorflow_federated.v0.DisposeResponse")
	proto.RegisterType((*SetCardinalitiesRequest)(nil), "tensorflow_federated.v0.SetCardinalitiesRequest")
	proto.RegisterType((*SetCardinalitiesRequest_Cardinality)(nil), "tensorflow_federated.v0.SetCardinalitiesRequest.Cardinality")
	proto.RegisterType((*SetCardinalitiesResponse)(nil), "tensorflow_federated.v0.SetCardinalitiesResponse")
	proto.RegisterType((*Value)(nil), "tensorflow_federated.v0.Value")
	proto.RegisterType((*Value_Struct)(nil), "tensorflow_federated.v0.Value.Struct")
	proto.RegisterType((*Value_Struct_Element)(nil), "tensorflow_federated.v0.Value.Struct.Element")
	proto.RegisterType((*Value_Sequence)(nil), "tensorflow_federated.v0.Value.Sequence")
	proto.RegisterType((*Value_Federated)(nil), "tensorflow_federated.v0.Value.Federated")
	proto.RegisterType((*ValueRef)(nil), "tensorflow_federated.v0.ValueRef")
}

func init() {
	proto.RegisterFile("tensorflow_federated/proto/v0/executor.proto", fileDescriptor_358ff774449af02a)
}

var fileDescriptor_358ff774449af02a = []byte{
	// 1136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x98, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0xc7, 0xed, 0x74, 0x73, 0x3b, 0xe9, 0x36, 0xed, 0xa1, 0xda, 0x06, 0x4b, 0xa0, 0x62, 0x01,
	0x8d, 0xd8, 0xae, 0x53, 0xca, 0x3e, 0x21, 0x04, 0xa5, 0x17, 0x36, 0x42, 0xda, 0xaa, 0xb8, 0x65,
	0x25, 0x24, 0x16, 0xe3, 0xda, 0x93, 0x2a, 0xc8, 0xb1, 0xb3, 0xbe, 0x84, 0x0d, 0x12, 0x4f, 0x88,
	0xb7, 0x7d, 0xe5, 0x99, 0x37, 0x3e, 0x09, 0x5f, 0x85, 0x77, 0x3e, 0x02, 0xf2, 0xcc, 0xf8, 0xda,
	0xb8, 0xb6, 0xe9, 0x5b, 0x3d, 0x73, 0xce, 0x6f, 0x66, 0x4e, 0xfe, 0x73, 0xce, 0x99, 0xc2, 0xbe,
	0x4f, 0x6c, 0xcf, 0x71, 0x27, 0x96, 0xf3, 0xb3, 0x36, 0x21, 0x26, 0x71, 0x75, 0x9f, 0x98, 0xa3,
	0xb9, 0xeb, 0xf8, 0xce, 0x68, 0x71, 0x30, 0x22, 0xaf, 0x89, 0x11, 0xf8, 0x8e, 0xab, 0xd0, 0x11,
	0xdc, 0x59, 0x65, 0xad, 0x2c, 0x0e, 0xa4, 0xb7, 0x6f, 0x1c, 0xe7, 0xc6, 0x22, 0xcc, 0xf1, 0x3a,
	0x98, 0x8c, 0x74, 0x7b, 0xc9, 0x7c, 0xa4, 0xd1, 0xdd, 0x2b, 0x18, 0xce, 0x6c, 0x1e, 0xf8, 0xba,
	0x3f, 0x75, 0x6c, 0xe6, 0x20, 0xff, 0xd6, 0x84, 0x8d, 0x33, 0xba, 0x2e, 0x51, 0xc9, 0xab, 0x80,
	0x78, 0x3e, 0x5e, 0xc0, 0xba, 0xe1, 0x12, 0xdd, 0x27, 0xda, 0x42, 0xb7, 0x02, 0x32, 0x10, 0x77,
	0xc5, 0x61, 0xef, 0xf0, 0xb1, 0x52, 0xb0, 0x1d, 0xe5, 0x84, 0x1a, 0xbf, 0x08, 0x6d, 0x39, 0x62,
	0x2c, 0xa8, 0x3d, 0x23, 0x19, 0xc5, 0xe7, 0xc0, 0x3f, 0x35, 0x43, 0xb7, 0xac, 0x41, 0x83, 0x02,
	0x3f, 0x2a, 0x01, 0x9e, 0xe8, 0x96, 0x95, 0xf0, 0xc0, 0x88, 0x07, 0xf1, 0x12, 0x1e, 0x72, 0x9c,
	0xe7, 0xbb, 0x81, 0xe1, 0x0f, 0xd6, 0x28, 0x70, 0xbf, 0x04, 0x78, 0x49, 0x8d, 0x13, 0x24, 0x3f,
	0x25, 0x1b, 0xc6, 0xef, 0x61, 0x33, 0x82, 0x12, 0x8b, 0x18, 0x61, 0x88, 0x06, 0x0f, 0x28, 0x77,
	0x54, 0xc6, 0x8d, 0xec, 0x13, 0x74, 0xdf, 0xc8, 0xce, 0xe0, 0x09, 0xb4, 0x59, 0xec, 0xc9, 0xa0,
	0x49, 0xa1, 0x7b, 0xc5, 0x50, 0x66, 0x97, 0xc0, 0x22, 0xcf, 0x10, 0x62, 0x4e, 0xbd, 0xb9, 0xe3,
	0x91, 0x41, 0xbb, 0x04, 0x72, 0xca, 0xec, 0x52, 0x10, 0xee, 0x89, 0x1a, 0x6c, 0x79, 0xc4, 0xd7,
	0x0c, 0xdd, 0x35, 0xa7, 0xb6, 0x6e, 0x4d, 0xfd, 0x29, 0xf1, 0x06, 0x1d, 0x8a, 0x3b, 0x28, 0xc4,
	0x5d, 0x12, 0xff, 0x24, 0xed, 0x90, 0x70, 0x37, 0xbd, 0xdc, 0x14, 0xee, 0x41, 0xdf, 0x0b, 0xa7,
	0x6d, 0x83, 0x68, 0x76, 0x30, 0xbb, 0x26, 0xee, 0xa0, 0xb5, 0x2b, 0x0e, 0x9b, 0xea, 0x46, 0x34,
	0x7c, 0x4e, 0x47, 0x8f, 0xbb, 0xd0, 0x76, 0x19, 0x47, 0x7e, 0xd3, 0x84, 0x7e, 0xac, 0x42, 0x6f,
	0xee, 0xd8, 0x1e, 0xc1, 0x6f, 0x56, 0xca, 0x70, 0xbf, 0x9a, 0x0c, 0x19, 0x23, 0xaf, 0xc3, 0xf3,
	0x55, 0x3a, 0x7c, 0x5c, 0x49, 0x87, 0x31, 0x30, 0x2d, 0xc4, 0xab, 0xd5, 0x42, 0x7c, 0x52, 0x51,
	0x88, 0x31, 0x33, 0xab, 0xc4, 0x97, 0x85, 0x4a, 0x3c, 0xa8, 0xae, 0xc4, 0x98, 0x7d, 0x4b, 0x8a,
	0xa7, 0x79, 0x29, 0x0e, 0xcb, 0xa5, 0x18, 0xd3, 0x62, 0x2d, 0x9e, 0xe6, 0xb5, 0x38, 0x2c, 0xd7,
	0x62, 0x42, 0x89, 0xc4, 0xf8, 0x63, 0xb1, 0x18, 0x3f, 0xae, 0x21, 0xc6, 0x18, 0x7c, 0x0f, 0x35,
	0x02, 0x74, 0x5c, 0x0e, 0x92, 0xbf, 0x06, 0xbc, 0x9d, 0xd4, 0xf0, 0x29, 0x34, 0xd3, 0x4a, 0x7c,
	0xb7, 0x70, 0x83, 0xcc, 0x8b, 0x19, 0xcb, 0xdf, 0xc2, 0x5b, 0x2b, 0x94, 0x89, 0x9f, 0x43, 0x97,
	0xce, 0x6b, 0x2e, 0x99, 0x70, 0xe0, 0x7b, 0x25, 0x40, 0x32, 0x51, 0x3b, 0x0b, 0xfe, 0x97, 0xfc,
	0xa7, 0x08, 0x5b, 0xb7, 0xf2, 0x24, 0x9e, 0xc2, 0xfa, 0x24, 0xb0, 0xe9, 0xef, 0x5c, 0x0f, 0xdc,
	0x8b, 0xdc, 0x54, 0x32, 0x09, 0x29, 0xba, 0x7b, 0x13, 0xcc, 0x88, 0xed, 0x53, 0x4a, 0xa3, 0x32,
	0x25, 0x72, 0x0b, 0x77, 0x78, 0x15, 0x05, 0x31, 0x7d, 0x81, 0xee, 0x7d, 0xee, 0xbf, 0xc5, 0x28,
	0x9e, 0x99, 0x74, 0x8e, 0xe7, 0xd0, 0x26, 0x16, 0x09, 0xd7, 0x1e, 0x88, 0xbb, 0x6b, 0xc3, 0xde,
	0xe1, 0xd3, 0x3a, 0xd5, 0x40, 0x39, 0x63, 0xbe, 0x6a, 0x04, 0x91, 0x5e, 0x42, 0x9b, 0x8f, 0x21,
	0xc2, 0x03, 0x5b, 0x9f, 0xb1, 0x9f, 0xbd, 0xab, 0xd2, 0xbf, 0xb3, 0xc7, 0x68, 0xd4, 0x3f, 0xc6,
	0x0b, 0xd8, 0x5e, 0x95, 0x0b, 0xee, 0x1d, 0x9e, 0x3f, 0x44, 0x78, 0xb4, 0xba, 0x2a, 0xe1, 0x11,
	0x80, 0xe7, 0x04, 0xae, 0x51, 0x93, 0xdd, 0x65, 0x4e, 0xa1, 0x2e, 0xb6, 0x79, 0x20, 0xc2, 0xf3,
	0x76, 0xc7, 0x02, 0x0f, 0xc5, 0x23, 0x68, 0x4e, 0x6d, 0x93, 0xbc, 0xa6, 0xc9, 0xaf, 0x39, 0x16,
	0x54, 0xf6, 0x79, 0xdc, 0x83, 0x6e, 0x9c, 0xbf, 0xe4, 0xef, 0x60, 0xa7, 0x20, 0x45, 0xdd, 0xfb,
	0xc8, 0x17, 0xb0, 0x91, 0x2d, 0x99, 0xf7, 0x26, 0x3e, 0x83, 0x7e, 0x2e, 0xf3, 0xfd, 0xcf, 0xbb,
	0x7f, 0x01, 0x1b, 0xd9, 0x42, 0x9c, 0xdf, 0xda, 0x5a, 0xdd, 0xad, 0x6d, 0x41, 0x3f, 0x97, 0x4e,
	0xe5, 0x7f, 0x45, 0xd8, 0x29, 0xa8, 0xcf, 0x78, 0x0d, 0x0f, 0xb3, 0xb9, 0x95, 0x2d, 0xf9, 0x59,
	0xdd, 0x42, 0xaf, 0x24, 0x83, 0x4b, 0x35, 0x8b, 0x94, 0x5e, 0x41, 0x2f, 0x35, 0x8b, 0x47, 0xd0,
	0x9d, 0x5b, 0xba, 0x11, 0x5d, 0xc5, 0x30, 0x5a, 0x72, 0xe1, 0x72, 0x17, 0x91, 0xa5, 0x9a, 0x38,
	0xe1, 0x2e, 0xf4, 0x92, 0x15, 0x96, 0x54, 0x6d, 0x4d, 0x35, 0x3d, 0x24, 0x4b, 0x30, 0x28, 0x2a,
	0x02, 0xf2, 0x9b, 0x16, 0x34, 0x59, 0xb5, 0x57, 0xa0, 0xc5, 0xd6, 0xe5, 0xdb, 0xd8, 0x56, 0x58,
	0xdf, 0xac, 0x44, 0x7d, 0xb3, 0xf2, 0xa5, 0xbd, 0x1c, 0x0b, 0x2a, 0xb7, 0xc2, 0x31, 0xf4, 0x52,
	0xfd, 0x31, 0xbf, 0xd5, 0xef, 0x97, 0x14, 0x47, 0x6a, 0x4b, 0xfb, 0x8c, 0xe4, 0x13, 0xbf, 0x80,
	0x56, 0xa6, 0x21, 0xf8, 0xe0, 0xee, 0x9f, 0x58, 0x61, 0x49, 0x20, 0xdc, 0x0a, 0x73, 0xc3, 0x33,
	0xe8, 0x44, 0xe5, 0x89, 0x97, 0xfe, 0xbd, 0x32, 0x04, 0x37, 0x1f, 0x0b, 0x6a, 0xec, 0x8a, 0x63,
	0xe8, 0xc6, 0xa6, 0xa5, 0xc5, 0x9e, 0x71, 0xbe, 0x8a, 0x86, 0xc6, 0x82, 0x9a, 0x38, 0x4b, 0x7f,
	0x89, 0xd0, 0xe2, 0xed, 0xc9, 0xb3, 0x7c, 0xa6, 0x7d, 0x52, 0xe9, 0x74, 0xb7, 0x53, 0xec, 0xe5,
	0xdd, 0x29, 0x36, 0xbe, 0x72, 0x8d, 0x1a, 0x57, 0x4e, 0xfa, 0x5d, 0x84, 0x4e, 0x14, 0x0b, 0x54,
	0x00, 0x7f, 0x99, 0xce, 0xe7, 0xc4, 0xd4, 0x3c, 0x7d, 0x41, 0x4c, 0x6d, 0xe6, 0x98, 0xc4, 0xa2,
	0x8b, 0xac, 0x87, 0xcd, 0x02, 0x9b, 0xbb, 0x0c, 0xa7, 0x9e, 0x87, 0x33, 0x78, 0x04, 0xeb, 0x7c,
	0x73, 0x9a, 0xbf, 0x9c, 0x47, 0x2b, 0xbf, 0x53, 0xb8, 0xf2, 0xd5, 0x72, 0x4e, 0xd4, 0x1e, 0x77,
	0x09, 0x3f, 0x8e, 0xdb, 0x7c, 0xd3, 0xd2, 0xaf, 0xd0, 0x8d, 0x43, 0x89, 0x9f, 0xc2, 0x03, 0xca,
	0x63, 0x3a, 0xfc, 0xb0, 0x90, 0x17, 0x7b, 0x50, 0x30, 0xf5, 0x49, 0x87, 0x61, 0xad, 0x72, 0x18,
	0xe2, 0x7d, 0xc8, 0x12, 0x74, 0xa2, 0x34, 0x82, 0x1b, 0xd0, 0x98, 0x9a, 0x3c, 0xc6, 0x8d, 0xa9,
	0x79, 0xf8, 0x4f, 0x0b, 0x3a, 0x67, 0xfc, 0xcd, 0x89, 0x3f, 0x41, 0x2f, 0xd5, 0xa7, 0x60, 0x9d,
	0xe7, 0x9e, 0x54, 0xab, 0x29, 0x97, 0x05, 0xbc, 0x01, 0x48, 0x5a, 0x03, 0xac, 0xf1, 0x10, 0x94,
	0xea, 0x34, 0xeb, 0xb2, 0x80, 0x33, 0x58, 0x4f, 0x97, 0x59, 0xac, 0xf5, 0x44, 0x94, 0xea, 0xf5,
	0xf1, 0xb2, 0x80, 0x0b, 0xe8, 0xe7, 0xaa, 0x1c, 0xd6, 0x7d, 0x3c, 0x4a, 0xb5, 0x7b, 0x7c, 0x59,
	0xc0, 0x1f, 0xa0, 0xcd, 0x0b, 0x16, 0x56, 0x7d, 0x57, 0x4a, 0x95, 0xbb, 0x7e, 0x59, 0xc0, 0x25,
	0x6c, 0xe6, 0xf3, 0x2d, 0xd6, 0x7e, 0x2c, 0x4a, 0xf5, 0x3b, 0x7a, 0x76, 0x34, 0x5e, 0xf0, 0xb0,
	0xea, 0x6b, 0x57, 0xaa, 0xfc, 0x14, 0x91, 0x05, 0xbc, 0x86, 0x36, 0x7f, 0x78, 0xde, 0xc1, 0xcf,
	0xfe, 0x83, 0xe4, 0x0e, 0x7e, 0xee, 0x0d, 0x2b, 0x0b, 0x43, 0xf1, 0x40, 0xbc, 0x6e, 0xd1, 0x82,
	0xf3, 0xc9, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xca, 0x9d, 0x88, 0xff, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExecutorClient is the client API for Executor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExecutorClient interface {
	CreateValue(ctx context.Context, in *CreateValueRequest, opts ...grpc.CallOption) (*CreateValueResponse, error)
	CreateCall(ctx context.Context, in *CreateCallRequest, opts ...grpc.CallOption) (*CreateCallResponse, error)
	CreateStruct(ctx context.Context, in *CreateStructRequest, opts ...grpc.CallOption) (*CreateStructResponse, error)
	CreateSelection(ctx context.Context, in *CreateSelectionRequest, opts ...grpc.CallOption) (*CreateSelectionResponse, error)
	Compute(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*ComputeResponse, error)
	SetCardinalities(ctx context.Context, in *SetCardinalitiesRequest, opts ...grpc.CallOption) (*SetCardinalitiesResponse, error)
	Dispose(ctx context.Context, in *DisposeRequest, opts ...grpc.CallOption) (*DisposeResponse, error)
	Execute(ctx context.Context, opts ...grpc.CallOption) (Executor_ExecuteClient, error)
}

type executorClient struct {
	cc *grpc.ClientConn
}

func NewExecutorClient(cc *grpc.ClientConn) ExecutorClient {
	return &executorClient{cc}
}

func (c *executorClient) CreateValue(ctx context.Context, in *CreateValueRequest, opts ...grpc.CallOption) (*CreateValueResponse, error) {
	out := new(CreateValueResponse)
	err := c.cc.Invoke(ctx, "/tensorflow_federated.v0.Executor/CreateValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) CreateCall(ctx context.Context, in *CreateCallRequest, opts ...grpc.CallOption) (*CreateCallResponse, error) {
	out := new(CreateCallResponse)
	err := c.cc.Invoke(ctx, "/tensorflow_federated.v0.Executor/CreateCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) CreateStruct(ctx context.Context, in *CreateStructRequest, opts ...grpc.CallOption) (*CreateStructResponse, error) {
	out := new(CreateStructResponse)
	err := c.cc.Invoke(ctx, "/tensorflow_federated.v0.Executor/CreateStruct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) CreateSelection(ctx context.Context, in *CreateSelectionRequest, opts ...grpc.CallOption) (*CreateSelectionResponse, error) {
	out := new(CreateSelectionResponse)
	err := c.cc.Invoke(ctx, "/tensorflow_federated.v0.Executor/CreateSelection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) Compute(ctx context.Context, in *ComputeRequest, opts ...grpc.CallOption) (*ComputeResponse, error) {
	out := new(ComputeResponse)
	err := c.cc.Invoke(ctx, "/tensorflow_federated.v0.Executor/Compute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) SetCardinalities(ctx context.Context, in *SetCardinalitiesRequest, opts ...grpc.CallOption) (*SetCardinalitiesResponse, error) {
	out := new(SetCardinalitiesResponse)
	err := c.cc.Invoke(ctx, "/tensorflow_federated.v0.Executor/SetCardinalities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) Dispose(ctx context.Context, in *DisposeRequest, opts ...grpc.CallOption) (*DisposeResponse, error) {
	out := new(DisposeResponse)
	err := c.cc.Invoke(ctx, "/tensorflow_federated.v0.Executor/Dispose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) Execute(ctx context.Context, opts ...grpc.CallOption) (Executor_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Executor_serviceDesc.Streams[0], "/tensorflow_federated.v0.Executor/Execute", opts...)
	if err != nil {
		return nil, err
	}
	x := &executorExecuteClient{stream}
	return x, nil
}

type Executor_ExecuteClient interface {
	Send(*ExecuteRequest) error
	Recv() (*ExecuteResponse, error)
	grpc.ClientStream
}

type executorExecuteClient struct {
	grpc.ClientStream
}

func (x *executorExecuteClient) Send(m *ExecuteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *executorExecuteClient) Recv() (*ExecuteResponse, error) {
	m := new(ExecuteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExecutorServer is the server API for Executor service.
type ExecutorServer interface {
	CreateValue(context.Context, *CreateValueRequest) (*CreateValueResponse, error)
	CreateCall(context.Context, *CreateCallRequest) (*CreateCallResponse, error)
	CreateStruct(context.Context, *CreateStructRequest) (*CreateStructResponse, error)
	CreateSelection(context.Context, *CreateSelectionRequest) (*CreateSelectionResponse, error)
	Compute(context.Context, *ComputeRequest) (*ComputeResponse, error)
	SetCardinalities(context.Context, *SetCardinalitiesRequest) (*SetCardinalitiesResponse, error)
	Dispose(context.Context, *DisposeRequest) (*DisposeResponse, error)
	Execute(Executor_ExecuteServer) error
}

func RegisterExecutorServer(s *grpc.Server, srv ExecutorServer) {
	s.RegisterService(&_Executor_serviceDesc, srv)
}

func _Executor_CreateValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).CreateValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow_federated.v0.Executor/CreateValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).CreateValue(ctx, req.(*CreateValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_CreateCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).CreateCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow_federated.v0.Executor/CreateCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).CreateCall(ctx, req.(*CreateCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_CreateStruct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStructRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).CreateStruct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow_federated.v0.Executor/CreateStruct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).CreateStruct(ctx, req.(*CreateStructRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_CreateSelection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).CreateSelection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow_federated.v0.Executor/CreateSelection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).CreateSelection(ctx, req.(*CreateSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_Compute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).Compute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow_federated.v0.Executor/Compute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).Compute(ctx, req.(*ComputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_SetCardinalities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCardinalitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).SetCardinalities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow_federated.v0.Executor/SetCardinalities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).SetCardinalities(ctx, req.(*SetCardinalitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_Dispose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).Dispose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow_federated.v0.Executor/Dispose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).Dispose(ctx, req.(*DisposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecutorServer).Execute(&executorExecuteServer{stream})
}

type Executor_ExecuteServer interface {
	Send(*ExecuteResponse) error
	Recv() (*ExecuteRequest, error)
	grpc.ServerStream
}

type executorExecuteServer struct {
	grpc.ServerStream
}

func (x *executorExecuteServer) Send(m *ExecuteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *executorExecuteServer) Recv() (*ExecuteRequest, error) {
	m := new(ExecuteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Executor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tensorflow_federated.v0.Executor",
	HandlerType: (*ExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateValue",
			Handler:    _Executor_CreateValue_Handler,
		},
		{
			MethodName: "CreateCall",
			Handler:    _Executor_CreateCall_Handler,
		},
		{
			MethodName: "CreateStruct",
			Handler:    _Executor_CreateStruct_Handler,
		},
		{
			MethodName: "CreateSelection",
			Handler:    _Executor_CreateSelection_Handler,
		},
		{
			MethodName: "Compute",
			Handler:    _Executor_Compute_Handler,
		},
		{
			MethodName: "SetCardinalities",
			Handler:    _Executor_SetCardinalities_Handler,
		},
		{
			MethodName: "Dispose",
			Handler:    _Executor_Dispose_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _Executor_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tensorflow_federated/proto/v0/executor.proto",
}
